### ISSUE TITLE
the return value of model score is not a number

### ISSUE THREAD

**Issue by qingfengpai** [RaRe-Technologies/gensim#1246] opened 2017-03-29 12:42 UTC
#### Description

in the document, the use of `model.score()` is below

```python
>>> model.score(["The fox jumped over a lazy dog".split()])
0.2158356
```

it return an array when i use, and the number is negative

#### Code

```python
from gensim.models import word2vec

entences = word2vec.Text8Corpus("./chain.txt")
model = word2vec.Word2Vec(sentences, size=200, hs=1, negative=0, min_count=1)
model.score(['3193458 1709044 105928'.split()]) 
```
#### chain.txt content
```
872570 1529576 561778 2828684
872570 3260863 46316 1819082 2219027 1779404 613548 3262529
872570 3077346 2361833 2310017
872570 905040 1568872 2310857 3641744
872570 1709044 1806846 4842891 4720850 1555695
872570 1709044 4707580 4131645 4365573
3193458 4258957 3897532 4534212 3260863 4361451 3018081 3070114 1502721
3193458 4534212 3260863 46316 1819082 3531169 4265935 3263769 2811061
3193458 2632976 2181967 2549981 4085742
3193458 1590012 2717046 4557209
```

#### Actual Results

```
array([-10.22072506], dtype=float32)
```

#### Versions

- platform: Linux-4.4.0-63-generic-x86_64-with-Ubuntu-14.04-trusty
- sys: Python 3.4.3, GCC 4.8.4
- numpy 1.12.0
- SciPy 0.19.0
- gensim 0.13.4.1
- FAST_VERSION 1

**Comment by gojomo** [comment] 2017-03-29 20:01
Since `score()` can take a sequence of multiple sentences, and returns scores for each of them in order, its return values are also sequences. Since you're providing a list with one sentence, you're getting back an array with one score. (If you provide a list with two sentences, you'll get back an array with two scores, etc.) 

Also, since the scores are the *log*-likelihood of a sentence, negative values are to be expected. You may want to exponentiate the values, as in the [demo notebook](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/deepir.ipynb)'s `docprob()` function (cell # 10)

So, you are seeing the proper expected behavior of `score()`.

(Is that all correct, @mataddy?)

**Comment by mataddy** [comment] 2017-03-29 20:18
sounds perfect to me @gojomo

**Comment by tmylk** [comment] 2017-03-29 23:37
Closing as "not an issue".
BTW please consider upgrading to 1.0.1

**Closed by tmylk** 2017-03-29 23:37 UTC

**Comment by qingfengpai** [comment] 2017-03-30 06:41
@gojomo thanks for your help

 i am still have some question, i want get the probability of a sentence under this model, how can i get a probability of number bewteen 0 - 1

this is my code

```python
sentence = "3193458, 1709044 105928 2650840"
llhd = np.array( model.score([sentence.split()]) )
lhd = np.exp(llhd - llhd.max(axis=0))
prob = pd.DataFrame( (lhd/lhd.sum(axis=0)).transpose() )
print (prob)
```
but the result is

```
    0
0  1.0
```


Look forward to your reply

**Comment by gojomo** [comment] 2017-03-31 20:00
I'm not sure that's strictly possible. The example notebook considers the case where a sentence *definitely* fits into one of the 5 classes (models). So it considers the 5 different log-likelihoods, after scaling and exponentiation, to result in probabilities totaling 1.0. Perhaps in that case the resulting per-class probabilities are realistic, or at least the largest one, and rank ordering, are plausibly correct. 

However, if you just have one model, the likelihoods you get should be comparable to other sentences (that are more or less likely within that model), but may not be reducible to a 0.0-1.0 absolute probability. There's no other structure/constraint to provide the alternative(s) that together cover all possibilities.
