### ISSUE TITLE
Bug report of gensim official webpage

### ISSUE THREAD

**Issue by yftadyz** [RaRe-Technologies/gensim#2985] opened 2020-10-19 06:31 UTC
https://radimrehurek.com/gensim/auto_examples/core/run_similarity_queries.html#sphx-glr-auto-examples-core-run-similarity-queries-py

In this page, at the last second code part,  the original code is :
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims):
    print(s, documents[i])

However, I guess here code should be:
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims):
    print(s, documents[s[0]])

**Comment by piskvorky** [comment] 2020-10-19 08:09
Thanks for reporting! Duplicate of #2699, already fixed.

**Closed by piskvorky** 2020-10-19 08:09 UTC
