### ISSUE TITLE
Can't import gensim in Windows

### ISSUE THREAD

**Issue by ibrahimsharaf** [RaRe-Technologies/gensim#2309] opened 2018-12-25 12:42 UTC
#### Description

I have a problem importing gensim, I use Anaconda in Windows (separate virtualenv), find below the traceback and the dependencies versions.

#### Steps/Code/Corpus to Reproduce

`import gensim`

#### Actual Results

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\models\__init__.py", line 15, in <module>
    from .doc2vec import Doc2Vec  # noqa:F401
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\models\doc2vec.py", line 86, in <module>
    from gensim.models.doc2vec_inner import train_document_dbow, train_document_dm, train_document_dm_concat
  File "__init__.pxd", line 872, in init gensim.models.doc2vec_inner
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

#### Versions

Windows-10-10.0.15063-SP0
Python 3.7.1 
NumPy 1.15.4
SciPy 1.2.0
gensim 3.6.0

**Comment by ibrahimsharaf** [comment] 2018-12-25 12:45
My conda list output, for a detailed look on versions:
```
asn1crypto                0.24.0                    <pip>
astroid                   2.1.0                    py37_0
atomicwrites              1.2.1                     <pip>
attrs                     18.2.0                    <pip>
boto                      2.49.0                    <pip>
boto3                     1.9.71                    <pip>
botocore                  1.12.71                   <pip>
bz2file                   0.98                      <pip>
ca-certificates           2018.03.07                    0
certifi                   2018.11.29               py37_0
cffi                      1.11.5                    <pip>
chardet                   3.0.4                     <pip>
colorama                  0.4.1                    py37_0
coverage                  4.5.2                     <pip>
cryptography              2.4.2                     <pip>
Cython                    0.29.1                    <pip>
distro                    1.3.0                     <pip>
docutils                  0.14                      <pip>
flake8                    3.6.0                     <pip>
gensim                    3.6.0                     <pip>
google-compute-engine     2.8.12                    <pip>
idna                      2.8                       <pip>
isort                     4.3.4                    py37_0
jmespath                  0.9.3                     <pip>
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
mccabe                    0.6.1                    py37_1
more-itertools            4.3.0                     <pip>
numpy                     1.15.4                    <pip>
openssl                   1.1.1a               he774522_0
pip                       18.1                     py37_0
pluggy                    0.8.0                     <pip>
py                        1.7.0                     <pip>
pycodestyle               2.4.0                     <pip>
pycparser                 2.19                      <pip>
pyemd                     0.5.1                     <pip>
pyflakes                  2.0.0                     <pip>
pylint                    2.2.2                    py37_0
pyOpenSSL                 18.0.0                    <pip>
pytest                    4.0.1                     <pip>
python                    3.7.1                h8c8aaf0_6
python-dateutil           2.7.5                     <pip>
requests                  2.21.0                    <pip>
requests-mock             1.5.2                     <pip>
s3transfer                0.1.13                    <pip>
scipy                     1.2.0                     <pip>
setuptools                40.6.3                   py37_0
six                       1.12.0                    <pip>
six                       1.12.0                   py37_0
smart-open                1.7.1                     <pip>
sqlite                    3.26.0               he774522_0
urllib3                   1.24.1                    <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py37_0
wincertstore              0.2                      py37_0
wrapt                     1.10.11          py37hfa6e2cd_2
```

**Comment by ibrahimsharaf** [comment] 2018-12-26 11:33
Same problem? @menshikh-iv 

```
C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\corpora\__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\corpora\indexedcorpus.py", line 15, in <module>
    from gensim import interfaces, utils
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\interfaces.py", line 21, in <module>
    from gensim import utils, matutils
  File "C:\Users\hatem\Anaconda3\envs\crashsim\lib\site-packages\gensim\matutils.py", line 1076, in <module>
    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "__init__.pxd", line 872, in init gensim._matutils
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

**Comment by Vichoko** [comment] 2018-12-27 00:35
I have the same exact problem running Python 3.6 on a docker container with Django + Gensim.

Gensim==3.6.0
Numpy==1.14.2

Stack

**Comment by menshikh-iv** [comment] 2018-12-27 12:32
@Vichoko sorry, it works for me (no exceptions). Can you try to uninstall `pyemd` and try again?
@ibrahimsharaf How exactly you install gensim (pip or conda?), can you enable verbosity and show log of the installation process? Exact steps for reproducing an error can be really useful!

**Comment by piercefreeman** [comment] 2018-12-27 20:15
@menshikh-iv Minimum reproducible case on my end:

*Dockerfile*

```
FROM python:3
ADD app.py /
RUN pip install gensim
CMD [ "python", "./app.py" ]
```

*app.py*

```
import gensim
```


```
docker build -t gensim-import-error .
docker run gensim-import-error
```

**Comment by ibrahimsharaf** [comment] 2018-12-28 05:52
I uninstalled numpy, scipy, gensim and reinstalled gensim again using `conda install genism` instead of pip and now everything works fine, but gensim version is 3.4.0 not 3.6.0.

**Comment by ibrahimsharaf** [comment] 2018-12-28 05:52
I uninstalled numpy, scipy, gensim and reinstalled gensim again using conda install genism instead of pip and now everything works fine, but the newly installed gensim version is 3.4.0 not 3.6.0.

**Comment by Gilgames000** [comment] 2018-12-28 15:51
+1

**Comment by menshikh-iv** [comment] 2019-01-08 01:57
Workarounds for (2)
- Use `--pre` flag explicitly, in that case, you'll have  `numpy==1.16.0rc2` for both (build & install) -> no errors
- Install `numpy` first and gensim after (even without `--pre` flag), in that case -  `numpy==1.15.4` will be installed and used for both (build & install) -> no errors

**Comment by menshikh-iv** [comment] 2019-01-08 02:06
In that case, I close this issue, if workarounds don't help - feel free to re-open and fill the issue with new details.

**Closed by menshikh-iv** 2019-01-08 02:06 UTC

**Comment by Vichoko** [comment] 2019-01-12 21:02
I tried all 2 workarounds and got the same errors.
In the python enviromented with the errors, i uninstalled gensim and python with pip uninstall.
Then tried and got the same errors: 

> ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216


In this case i tried this in a docker image running in ubuntu.
