### ISSUE TITLE
Python11 can not install gensim, if it is possible, I wish Python11 can have the right version for gensim too

### ISSUE THREAD

**Issue by Victorrrrr86** [RaRe-Technologies/gensim#3411] opened 2022-12-09 08:38 UTC
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
print(my_model.lifecycle_events)
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by mpenkov** [comment] 2022-12-09 09:49
Duplicate of #3395

**Comment by Victorrrrr86** [comment] 2022-12-09 09:49
您好，我是关雄耀，您的邮件我已经收到。如果有紧急事情，请电话联系18719079514

**Closed by mpenkov** 2022-12-09 09:49 UTC
