### ISSUE TITLE
Update documentation for 4.0.0

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#2960] opened 2020-09-28 12:10 UTC
Internal checklist so I don't forget something:

- [x] Rewrite the landing page copy for the new website.
- [x] Restructure top-level TOC tree for the new website.
- [x] Make all `rst` docs up-to-date for the new website, check hyperlinks, update stats & copy.
- [x] Go over rendered API docs and check everything's up to date and makes sense: formatting, descriptions, notes, hyperlinks.
- [x] Migrate & regenerate all Tutorials and How-tos.
- [x] Write the [Migration guide](https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4).
- [x] Write the 4.0.0 release notes.
- [x] Improve the [Developer page](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page) with Gensim code-style: hanging indents, trailing commas, FIXME vs TODO, line length, etc.

**Comment by piskvorky** [comment] 2020-09-28 12:13
Fixes go into PR #2954.

**Comment by piskvorky** [comment] 2020-10-16 12:32
@mpenkov release notes below. Can you please add (auto-generate?) the `🔴 Bug fixes`  / `👍 Improvements`
/ `📚 Tutorial and doc improvements` / `⚠️ Deprecations` sections?

Next up, I'll fill in the performance numbers & finish the Migration guide, and we're ready to release 4.0.0beta. I don't think any of the other tickets are blocking (CC @gojomo).

## 1. Tweet

------

So, Gensim 4.0 is nearly here. Faster models, less RAM, prettier documentation.

Want to help? Install the pre-release and let us know!

pip install --pre --upgrade gensim

<link to the pre-release notes>

--------

## 2. Release notes (maybe also a blog post?)

--------

**⚠️ Gensim 4.0 contains breaking API changes! See the [Migration guide](FIXME) to migrate your existing Gensim 3.x code.**

Gensim 4.0 is a major release with lots of performance improvements, robustness and a [new website](FIXME new docs – kept side-by-side with 3.8.3 until the full release?) (finally!).

Main highlights (see also *👍 Improvements* below):

* Improved the most popular Gensim algorithms: [fastText](FIXME), [word2vec](FIXME), [doc2vec](FIXME), [phrases](FIXME). We did this:
  a) For efficiency. E.g. fastText & word2vec model training is now **10% faster** while using **FIXME % less RAM**. Phrases are more than 2x faster.
  b) To improve robustness. We fixed a bunch of long-standing bugs and inefficiencies by refactoring the internal code structure (see 🔴 Bug fixes below)

  Most of these updates come transparent aka "for free", but see [Migration guide](FIXME) for some changes that broke the 3.x API (mostly param renaming). **Update your code accordingly**.

* Dropped a bunch of contributed modules FIXME, FIXME, FIXME.
  - Mostly because their code quality was not up to our standards. Also there was no one to maintain them, answer user questions. So rather than let those modules rot, we took the hard decision of removing them from Gensim. If anyone's interested in maintaining them – feel free to fork them into your own repo, they can live happily outside of Gensim.

* Dropped Python 2. Gensim 4.0 is Py3.6+. Read our [Python version support policy](FIXME).
  - If you still need Python 2 for some reason, stay at [Gensim 3.8.3](https://github.com/RaRe-Technologies/gensim/releases/tag/3.8.3).

* Dropped all methods marked as deprecated in 3.x. They've been deprecated for more than a year now, it's time.

So, a major clean-up release overall. We're happy with this **tighter, leaner and faster Gensim**. It's the direction we'll keep going forward: less kitchen-sink of "latest academic algorithms", more focus on robust SW engineering, targetting common concrete NLP & document similarity use-cases.

### Why pre-release?

This 4.0.0beta pre-release is for users who want the cutting edge models: extra performance, bug fixes. Plus users who want to help out, by testing and providing feedback: code, documentation, workflows… Please let us know at the [mailing list](https://groups.google.com/forum/#!forum/gensim)!

Install with

```bash
pip install --pre --upgrade gensim
```

What will change between this pre-release and a "full" 4.0 release? Stability is important to Gensim, so we're improving the process of keeping backward compatibility of already-trained models. There'll be an explicit migration script between each `4.n` to `4.(n+1)` Gensim release. Check progress [here](https://github.com/RaRe-Technologies/gensim/milestone/3).


🔴 Bug fixes

👍 Improvements

📚 Tutorial and doc improvements

⚠️ Deprecations

-------

**Comment by gojomo** [comment] 2020-10-16 22:29
Nice progress! A few thoughts:

* I don't think Gensim's actually confirmed working yet in Python 3.9 - but by the stated policy, it should be. see #2966 for my quickie test, whose success may just be awaiting scipy catching up & distributing wheels
* Everywhere that offers the `pip install --pre` advice should include some boilerplate along the lines of: "if you find problems, please report them _ISSUES_, and if you need to roll-back, use pip command _EXAMPLE_"
* For the reasons I gave on the other issue, I fear too much [emphasis on the 'migration script'](https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility#upgrading-trained-models) may cause problems & extra work, implying there's more assurance than there is. It could successfully run, but silently leave models with problems that are only discovered later. On the other hand, even as an advocate of faster sunsetting of old-version compatibility, I think it is unlikely to be strictly true that people will regularly  "**have to** upgrade in multiple hops" (as written now). Much/most of the time, a load from many points back will still work. My goal is just to set the expectation that it's only **strongly-targetted** to work one-back, and older *may* require multiple hops, so that **some** version-increment-improvements can choose to trim their testing-effort & crufty-compatibility code. Not that, for example, 4.3 refuses to direct-load a 4.1-model even in a model class that's not been touched recently.

**Comment by piskvorky** [comment] 2020-10-16 23:01
Thanks. Re. migrations: I replied in #2967, to keep it tidy.

**Comment by mpenkov** [comment] 2020-10-17 05:25
> Can you please edit this comment to add (auto-generate?)

I think it's better to do this directly in the [changelog](https://github.com/RaRe-Technologies/gensim/blob/develop/CHANGELOG.md), because that gets version-controlled and is generally easier to edit than comments in a github PR. It already has some entries. I will double-check that everything merged after 3.8.3 is in there.

**Comment by piskvorky** [comment] 2020-10-17 09:15
Thanks. So to be clear, your proposed workflow is:

1. update Changelog.
2. copy / edit entries from the Changelog into the release notes sections here.

I was under the impression you had some script that takes PRs and auto-generates this list (which can then be edited). Was I confusing that with something else?

**Comment by mpenkov** [comment] 2020-10-17 09:37
> Thanks. So to be clear, your proposed workflow is:

Sort of.

> copy / edit entries from the Changelog into the appropriate release notes sections here.

Why do we need to copy them here? They can go straight into the release notes when we do the release.

> I was under the impression you had some script that takes merged PRs + closed tickets and auto-generates this list (which can then be edited). Was I confusing that with something else?

There's a script that takes a PR number and then grabs its title, etc. We use it for individual PRs - it's not quite what we need here, because there have been dozens of merged PRs since the last release.

**Comment by mpenkov** [comment] 2020-10-17 09:58
Please see #2981

**Comment by piskvorky** [comment] 2020-10-17 13:27
> Why do we need to copy them here?

Because I don't know what to put in the release notes :D 

Relying on my memory is not a good idea.

**Comment by mpenkov** [comment] 2020-10-18 10:26
Can't we just link to the changelog in the comment instead of copying?

The risk is we copy stuff to here, then change it in the changelog, and forget to update the comment.

**Comment by piskvorky** [comment] 2020-10-18 16:06
Yes. I can edit the changelog in #2981, instead of here.

**Comment by piskvorky** [comment] 2020-10-25 21:25
@gojomo @mpenkov I updated the Migration guide too: https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

There are two FIXMEs I still wasn't sure about, one for @gojomo and one for @mpenkov . Can you please have a look?

And fix / expand / improve anything else you might see in the guide. Thanks!

**Comment by gojomo** [comment] 2020-10-27 00:48
I addressed the FIXME with my name beside it, clarifying the `corpus_iterable` (instead of `sentences`/`documents`) change. This could possibly be listed higher - it's not really advanced, but it's also somewhat uncommon for that parameter to be passed as a named-parameter rather than positional. 

I also added extra clarification around `index2entity` & `vocab`, and a note about the removal of `.trainables`/`.vocabulary`. 

I think the commitment "*All* your existing stored models... will continue to work" is an overly-strong commitment, as our testing doesn't really guarantee that for all models/all features, and I doubt it will be expanded to guarantee that, and if some stray reports of problems with old/rare configurations come up, I know *I* won't have time to fix them. The truth is closer to: "most will work & we haven't gratuitously knowingly broken anything in recent/common use." 

(For example, some shallow testing of pre-1.0 models used to be present but I [disabled-via-renaming](https://github.com/RaRe-Technologies/gensim/blob/60a8f7f5599e241779b82f97d375a5046cb730c9/gensim/test/test_word2vec.py#L871) during other updates. Similarly. some [other testing of old-models-of-inexact-vintage is disabled](https://github.com/RaRe-Technologies/gensim/blob/60a8f7f5599e241779b82f97d375a5046cb730c9/gensim/test/test_word2vec.py#L319). Will these old models load & work? *Should* they work? Would re-enabling this test code actually test anything useful? I don't know, but I suspect it'd be a waste of time given the real possibility that there are zero people in the world who'd actually need this.)

Similarly, and for reasons I've also alluded to elsewhere, I think the process authoritatively described at <https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility#upgrading-trained-models> is somewhat over-involved for the common case. Usually, things will just work, no multiple-hops necessary, because most 4.X to 4.[X+1] releases won't even touch most models, and even where it does, we'll *try* to support forward-migration when practical. But in the occasional case where bigger changes happen and/or we didn't notice an issue, the guidance risks creating too much confidence in this "migration" script when it runs without error. That won't, practically, be a true guarantee everything is OK given our current (& foreseeable) level of testing. Saying less would be be more reasonable.

**Comment by piskvorky** [comment] 2020-10-27 10:20
Thanks.

What I meant is "if loading your model worked in 3.8.3, it will continue to work in 4.0.0". Of course we don't support *everything* meticulously (nor test for it, and I don't think anyone expects that either).

I'll check your links and reword as appropriate.

About https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility#upgrading-trained-models : discussion here https://github.com/RaRe-Technologies/gensim/issues/2967#issuecomment-710688660

**Comment by piskvorky** [comment] 2020-10-27 17:05
I checked your links and don't think that's something we need to draw attention, explicitly.

If there are any people who need to load models from Gensim<1.0 or some such "support", we can handle them on a case-by-case basis. I suspect there are none, just as you said.

**Comment by gojomo** [comment] 2020-10-27 20:35
My main concern is that we don't project a false confidence - to do so increases the risk of users being less vigilant in their upgrades, and increases the implied obligations about what might be fixed if buggy. 

The current wording without extra emphasis on "*all*... will work" is better than before, but my own preferred wording would still be "should work", implying a goal not a guarantee. More like: "Our goal has been that most older models should load & function as before, but you should independently verify that your models load & work, especially if older than 3.8.3". 

It's hair-splitting, but it just seems safer to me to lean in the direction of lower-expectation/lower-commitments.

**Comment by piskvorky** [comment] 2020-10-27 20:40
OK, I'll relax the language further. It's a Wiki page, so we can update it any time easily. I'm hoping the beta release will shine light on several places not covered by the migration guide, or not covered adequately.

Or nobody will care, which is also quite possible.

**Closed** 2020-10-28 12:35 UTC
Labels: documentation, housekeeping

**Comment by mpenkov** [comment] 2020-10-28 14:04
@piskvorky This got closed by automation: not sure if that's what we actually wanted to do, so double-checking.

**Comment by piskvorky** [comment] 2020-10-28 14:06
Yes, I'm done here.
