### ISSUE TITLE
'utf-8' codec can't decode byte 0xd1 in position 97: unexpected end of data

### ISSUE THREAD

**Issue by Barracuda72** [RaRe-Technologies/gensim#2452] opened 2019-04-19 09:03 UTC
#### Problem description

Ok, I have the stated issue. Yes, it's in FAQ, I know. But I think it's different for me.
The thing is: on one machine it occurs, on another one it isn't. On the exact same data that was produced by original word2vec and that is 100% pure organic utf-8.
The machine that _doesn't have_ this problem (my local Gentoo laptop) is using build from `master` branch produced sometimes around 21.04.2018. The machine that _have_ the problem (cluster machine on CentOS) has Gensim installed from pip, version 3.7.2. Python version 3.6 on both of them.

#### Steps/code/corpus to reproduce

```
Traceback (most recent call last):
  File "/home/scrambled/process_data.py", line 172, in <module>
    w2v = load_bin_vec(w2v_file, vocab)
  File "/home/scrambled/process_data.py", line 102, in load_bin_vec
    model = KeyedVectors.load_word2vec_format(fname, binary=True)
  File "/home/scrambled/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 1476, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/scrambled/.local/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 382, in _load_word2vec_format
    word = utils.to_unicode(b''.join(word), encoding=encoding, errors=unicode_errors)
  File "/home/scrambled/.local/lib/python3.6/site-packages/gensim/utils.py", line 359, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 97: unexpected end of data
```

#### Versions

Machine that _do have_ the problem:

```
Linux-2.6.32-696.30.1.el6.x86_64-x86_64-with-redhat-6.10-Santiago
Python 3.6.8 (default, Apr 18 2019, 15:17:38) [GCC 5.5.0]
NumPy 1.16.2
SciPy 1.2.1
gensim 3.7.2
>>> FAST_VERSION 1
```

Machine that _don't_:
```
Linux-4.18.11-x86_64-Intel-R-_Core-TM-_i7-7700HQ_CPU_@_2.80GHz-with-gentoo-2.6
Python 3.6.5 (default, Apr 25 2018, 22:51:58) [GCC 7.2.0]
NumPy 1.16.1
SciPy 1.2.1
gensim 3.4.0
FAST_VERSION 0
```

**Comment by Barracuda72** [comment] 2019-04-19 12:43
OK, I can confirm that something is wrong with newer Gensim versions themselves. Tried to install 3.7.2 into virtualenv onto my laptop and got the same problem. 3.4.0 works fine.

**Comment by mpenkov** [comment] 2019-04-20 07:04
What model are you attempting to load?

You've shown a stack trace, that helps us understand _where_ the problem is, but it doesn't help us reproduce it. Could you please provide a method for reproducing the problem? Ideally, this would be a minimal source code sample that we could paste into an interpreter and run.

**Comment by mpenkov** [comment] 2019-05-04 09:59
@Barracuda72 Can you please provide the information we need (see previous message)? Without it, we can't do anything about this ticket, and will have to close it.

**Comment by mpenkov** [comment] 2019-05-12 09:48
Closing due to inactivity.

**Closed by mpenkov** 2019-05-12 09:48 UTC
Labels: need info
