### ISSUE TITLE
model.wmdistance doesn't work after read model

### ISSUE THREAD

**Issue by slavadubrov** [RaRe-Technologies/gensim#1022] opened 2016-11-16 12:22 UTC
#### Import libraries

```python
import pandas as pd
import numpy as np
import gensim
import nltk

import matplotlib.pyplot as plt
%matplotlib inline
```

#### Read and preprocess text

```python
df = pd.read_csv("/path/to/initial/text/file.csv", sep="\t", error_bad_lines=False)
df = df.dropna()

# Import various modules for string cleaning
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return(words)

# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download()   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Define a function to split a review into parsed sentences
def review_to_sentences( review, tokenizer, remove_stopwords=False ):
    # Function to split a review into parsed sentences. Returns a 
    # list of sentences, where each sentence is a list of words
    #
    # 1. Use the NLTK tokenizer to split the paragraph into sentences
    raw_sentences = tokenizer.tokenize(review.strip())
    #
    # 2. Loop over each sentence
    sentences = []
    for raw_sentence in raw_sentences:
        # If a sentence is empty, skip it
        if len(raw_sentence) > 0:
            # Otherwise, call review_to_wordlist to get a list of words
            sentences.append( review_to_wordlist( raw_sentence, \
              remove_stopwords ))
    #
    # Return the list of sentences (each sentence is a list of words,
    # so this returns a list of lists
    return sentences

sentences = []  # Initialize an empty list of sentences

print("Parsing sentences from training set")
for abstract in df["abstract"]:
    sentences += review_to_sentences(abstract, tokenizer, True)
    
ds_sentences = pd.Series(sentences, name='sentences')

ds_sentences.to_csv("/path/to/preprocessed/text/file.csv", index=False)
```
### After text preprocessing I trained word2vec model

```python
%%time
# Import the built-in logging module and configure it so that Word2Vec 
# creates nice output messages
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s',\
    level=logging.INFO)

# Set values for various parameters
num_features = 300    # Word vector dimensionality                      
min_word_count = 40   # Minimum word count                        
num_workers = 4       # Number of threads to run in parallel
context = 10          # Context window size                                                                                    
downsampling = 1e-3   # Downsample setting for frequent words

# Initialize and train the model (this will take some time)
from gensim.models import word2vec
print("Training model...")
model = word2vec.Word2Vec(ds_sentences, workers=num_workers, \
            size=num_features, min_count = min_word_count, \
            window = context, sample = downsampling)

# If you don't plan to train the model any further, calling 
# init_sims will make the model much more memory-efficient.
model.init_sims(replace=True)

# It can be helpful to create a meaningful model name and 
# save the model for later use. You can load it later using Word2Vec.load()
model_name = "300features_40minwords_10context"
model.save("/path/to/model/" + model_name)
```
    CPU times: user 25min 38s, sys: 4.43 s, total: 25min 43s
    Wall time: 7min 56s

### And after training I can measure most similar words to some words

```python
model.most_similar(positive=["android"])
```

    [('iphone', 0.6860567927360535),
     ('app', 0.683183491230011),
     ('ios', 0.6697854995727539),
     ('symbian', 0.6537686586380005),
     ('apps', 0.6434202194213867),
     ('smartphone', 0.6431980133056641),
     ('blackberry', 0.6421018838882446),
     ('tizen', 0.6371567249298096),
     ('xamarin', 0.6090145111083984),
     ('phonegap', 0.6083793640136719)]

### And also find wmdistance

```python
model.wmdistance(ds_sentences.iloc[10], ds_sentences.iloc[110])
```
    1.2963280259150474

### I downloaded the saved w2v model

```python
model_name = "300features_40minwords_10context_initsims"
model = gensim.models.Word2Vec.load("/path/to/model/" + model_name)
```
### I downloaded preprocessed text

```python
ds_sentences = pd.read_csv("/path/to/preprocessed/text/file.csv", header=None, names=["sentences"])
ds_sentences.shape
```
    (5279750, 1)

### with it I can even find most_similar -> all work good

```python
model.most_similar(positive=["android"])
```

    [('iphone', 0.6860567927360535),
     ('app', 0.683183491230011),
     ('ios', 0.6697854995727539),
     ('symbian', 0.6537686586380005),
     ('apps', 0.6434202194213867),
     ('smartphone', 0.6431980133056641),
     ('blackberry', 0.6421018838882446),
     ('tizen', 0.6371567249298096),
     ('xamarin', 0.6090145111083984),
     ('phonegap', 0.6083793640136719)]

### But wmdistance doesn't work

```python
model.wmdistance(ds_sentences.iloc[10], ds_sentences.iloc[110])
```

    inf

**Comment by tmylk** [comment] 2016-11-18 09:36
Please add a INFO-level log. It will show the reasonf for inf

**Comment by slavadubrov** [comment] 2016-11-21 13:02
There is an example of logs after reading pretrained model and  preprocessed data.
### Load and work with model


```python
model_name = "300features_40minwords_10context_initsims"
model = gensim.models.Word2Vec.load("/path/to/model/" + model_name)
```

    2016-11-21 15:52:55,068 : INFO : loading Word2Vec object from /path/to/model/300features_40minwords_10context_initsims
    2016-11-21 15:52:55,812 : INFO : setting ignored attribute cum_table to None
    2016-11-21 15:52:55,816 : INFO : setting ignored attribute syn0norm to None
    2016-11-21 15:52:55,816 : INFO : loaded /path/to/model/300features_40minwords_10context_initsims



```python
ds_sentences = pd.read_csv("/path/to/preprocessed/text/file.csv", header=None, names=["sentences"])
ds_sentences.shape
```




    (5279750, 1)




```python
model.most_similar(positive=["android"])
```

    2016-11-21 15:53:05,382 : INFO : precomputing L2-norms of word weight vectors





    [('iphone', 0.6860567927360535),
     ('app', 0.683183491230011),
     ('ios', 0.6697854995727539),
     ('symbian', 0.6537686586380005),
     ('apps', 0.6434202194213867),
     ('smartphone', 0.6431980133056641),
     ('blackberry', 0.6421018838882446),
     ('tizen', 0.6371567249298096),
     ('xamarin', 0.6090145111083984),
     ('phonegap', 0.6083793640136719)]




```python
model.wmdistance(ds_sentences.iloc[10], ds_sentences.iloc[110])
```

    2016-11-21 15:53:07,091 : INFO : Removed 1 and 1 OOV words from document 1 and 2 (respectively).
    2016-11-21 15:53:07,093 : INFO : At least one of the documents had no words that werein the vocabulary. Aborting (returning inf).





    inf




```python

```

**Comment by slavadubrov** [comment] 2016-11-21 14:05
And syn0 isn't empty here:

```python
model.syn0
```




    array([[-0.03913694, -0.03426806,  0.01580884, ...,  0.05210079,
            -0.03693577,  0.01751983],
           [ 0.00326974, -0.02205359,  0.03564278, ...,  0.09804322,
            -0.12672497,  0.05011716],
           [-0.08086007,  0.03179216,  0.05238753, ...,  0.09354611,
            -0.03497601,  0.0230536 ],
           ..., 
           [-0.00155388, -0.05863547, -0.04253805, ..., -0.0973423 ,
            -0.02092007,  0.01950703],
           [-0.02800442, -0.14028312, -0.05008078, ..., -0.03252429,
            -0.01531981, -0.03621005],
           [ 0.07407176,  0.0193385 ,  0.00120981, ..., -0.04737007,
             0.00359498,  0.0160856 ]], dtype=float32)




```python

```

**Comment by tmylk** [comment] 2016-11-22 18:56
It [seems](https://github.com/RaRe-Technologies/gensim/blob/699773a78f32ff2c254cf16a586a5d26a08394fe/gensim/models/keyedvectors.py#L347) that `vocab` is empty.

**Comment by slavadubrov** [comment] 2016-11-25 07:19
I understood this. But why? And why data preprocessing repairs vocab?
Where in this part of code did it happen?

### Read and preprocess text


```python
df = pd.read_csv("/path/to/initial/text/file.csv", sep="\t", error_bad_lines=False)
df = df.dropna()

# Import various modules for string cleaning
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords

def review_to_wordlist( review, remove_stopwords=False ):
    # Function to convert a document to a sequence of words,
    # optionally removing stop words.  Returns a list of words.
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(review).get_text()
    #  
    # 2. Remove non-letters
    review_text = re.sub("[^a-zA-Z]"," ", review_text)
    #
    # 3. Convert words to lower case and split them
    words = review_text.lower().split()
    #
    # 4. Optionally remove stop words (false by default)
    if remove_stopwords:
        stops = set(stopwords.words("english"))
        words = [w for w in words if not w in stops]
    #
    # 5. Return a list of words
    return(words)

# Download the punkt tokenizer for sentence splitting
import nltk.data
nltk.download()   

# Load the punkt tokenizer
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

# Define a function to split a review into parsed sentences
def review_to_sentences( review, tokenizer, remove_stopwords=False ):
    # Function to split a review into parsed sentences. Returns a 
    # list of sentences, where each sentence is a list of words
    #
    # 1. Use the NLTK tokenizer to split the paragraph into sentences
    raw_sentences = tokenizer.tokenize(review.strip())
    #
    # 2. Loop over each sentence
    sentences = []
    for raw_sentence in raw_sentences:
        # If a sentence is empty, skip it
        if len(raw_sentence) > 0:
            # Otherwise, call review_to_wordlist to get a list of words
            sentences.append( review_to_wordlist( raw_sentence, \
              remove_stopwords ))
    #
    # Return the list of sentences (each sentence is a list of words,
    # so this returns a list of lists
    return sentences

sentences = []  # Initialize an empty list of sentences

print("Parsing sentences from training set")
for abstract in df["abstract"]:
    sentences += review_to_sentences(abstract, tokenizer, True)
    
ds_sentences = pd.Series(sentences, name='sentences')

ds_sentences.to_csv("/path/to/preprocessed/text/file.csv", index=False)
```

And if I don't use preprocessing and just download the preprocessed data the vocab is empty.
Like this:
```python
ds_sentences = pd.read_csv("/path/to/preprocessed/text/file.csv", header=None, names=["sentences"])
ds_sentences.shape
```

Why? What action repaired the Vocab?

**Comment by piskvorky** [comment] 2016-12-13 09:12
@tmylk ping

**Comment by vlejd** [comment] 2017-03-18 13:43
I  think the problem is related to pandas. Please check how does the  ds_sentences.iloc[10]  look like. In my case It converted all sentence tokens into one string "['some','tokens']".  When wmdistance tries to compute len  of this object, it returns 1. Iteration over this object returns only one element which is the "['some','tokens']" string. This string is obviously not in the vocabulary so the distance is inf.

**Comment by vlejd** [comment] 2017-03-18 13:49
I suggest using `ds_sentences.to_csv('/path/to/file)` and `pd.Series.from_csv('/path/to/file')`.

**Comment by tmylk** [comment] 2017-03-19 01:16
Thanks for the investigation @vlejd . Closing as not related to Gensim. Probably printing oov words in debug logging is a good idea. 
Hope @slavadubrov agrees with the resolution above.

**Closed by tmylk** 2017-03-19 01:16 UTC
Labels: bug
