### ISSUE TITLE
While Running LDA in between it throws an "IndexError" error.

### ISSUE THREAD

**Issue by gauravkoradiya** [RaRe-Technologies/gensim#2599] opened 2019-09-09 12:01 UTC
#### Problem description

What are you trying to achieve? 
:- I want to run LDA completely on Wiki-dataset. I have 43lakh of wiki document and have 90 lakh feature and 50lakh(filtered dictionary).

What is the expected result?
:- Output expectation is to extract topic at the end of training model.

 What are you seeing instead?
:-  Generates an error in between because of vocab size and feature len in MM are diffrent. How to resolve it?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

```
Traceback (most recent call last):
  File "D:/Projects/docs_handler/email_data_experiment.py", line 38, in <module>
    lda = LdaModel(corpus=corpus, num_topics=5, id2word=id2word,iterations=5,chunksize=100000,eval_every=0,update_every=2)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 521, in __init__
    self.update(corpus, chunks_as_numpy=use_numpy)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 983, in update
    gammat = self.do_estep(chunk, other)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 744, in do_estep
    gamma, sstats = self.inference(chunk, collect_sstats=True)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 681, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 5000000 is out of bounds for axis 1 with size 5000000
```
Log:
```
2019-09-09 17:20:56,008 : INFO : PROGRESS: pass 0, at document #1700000/4257515
2019-09-09 17:20:56,008 : INFO : Performing E-step
2019-09-09 17:21:13,868 : INFO : 0/100000 documents converged within 5 iterations
2019-09-09 17:21:13,936 : INFO : Finished E-step
2019-09-09 17:21:13,936 : INFO : performing M-step
2019-09-09 17:21:13,936 : INFO : finished M-step
2019-09-09 17:21:26,342 : INFO : PROGRESS: pass 0, at document #1800000/4257515
2019-09-09 17:21:26,348 : INFO : Performing E-step
2019-09-09 17:21:46,477 : INFO : 0/100000 documents converged within 5 iterations
2019-09-09 17:21:46,565 : INFO : Finished E-step
2019-09-09 17:21:46,565 : INFO : performing M-step
2019-09-09 17:21:46,566 : INFO : updating topics
2019-09-09 17:21:47,982 : INFO : merging changes from 200000 documents into a model of 4257515 documents
2019-09-09 17:21:49,516 : INFO : topic #0 (0.200): 0.005*"new" + 0.004*"school" + 0.004*"references" + 0.004*"league" + 0.003*"season" + 0.003*"university" + 0.003*"national" + 0.003*"american" + 0.003*"club" + 0.003*"born"
2019-09-09 17:21:49,602 : INFO : topic #1 (0.200): 0.005*"new" + 0.003*"time" + 0.003*"team" + 0.003*"year" + 0.002*"war" + 0.002*"references" + 0.002*"world" + 0.002*"links" + 0.002*"national" + 0.002*"later"
2019-09-09 17:21:49,677 : INFO : topic #2 (0.200): 0.002*"state" + 0.002*"new" + 0.002*"university" + 0.002*"references" + 0.002*"year" + 0.002*"used" + 0.002*"time" + 0.002*"city" + 0.002*"years" + 0.002*"known"
2019-09-09 17:21:49,758 : INFO : topic #3 (0.200): 0.003*"new" + 0.003*"school" + 0.003*"references" + 0.002*"years" + 0.002*"city" + 0.002*"station" + 0.002*"time" + 0.002*"united" + 0.002*"area" + 0.002*"north"
2019-09-09 17:21:49,846 : INFO : topic #4 (0.200): 0.004*"new" + 0.004*"album" + 0.004*"music" + 0.003*"released" + 0.003*"film" + 0.002*"song" + 0.002*"references" + 0.002*"time" + 0.002*"series" + 0.002*"links"
2019-09-09 17:21:49,958 : INFO : topic diff=0.062798, rho=0.242536
2019-09-09 17:21:49,986 : INFO : finished M-step
2019-09-09 17:22:02,037 : INFO : PROGRESS: pass 0, at document #1900000/4257515
2019-09-09 17:22:02,037 : INFO : Performing E-step
Traceback (most recent call last):
  File "D:/Projects/docs_handler/email_data_experiment.py", line 38, in <module>
    lda = LdaModel(corpus=corpus, num_topics=5, id2word=id2word,iterations=5,chunksize=100000,eval_every=0,update_every=2)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 521, in __init__
    self.update(corpus, chunks_as_numpy=use_numpy)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 983, in update
    gammat = self.do_estep(chunk, other)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 744, in do_estep
    gamma, sstats = self.inference(chunk, collect_sstats=True)
  File "C:\Users\koradg\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 681, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 5000000 is out of bounds for axis 1 with size 5000000
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)

Windows-10-10.0.17763-SP0
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
NumPy 1.17.0
SciPy 1.3.0
gensim 3.8.0
FAST_VERSION 0

```

I got this issue because of in MM i have (4300000*9000000) matrix and i have vocab size of 5000000. Can anyone give solution for this?

**Comment by piskvorky** [comment] 2019-09-09 14:53
I don't know what "lakh" is, please use standard unit.

But either way, it looks like there's some feature mismatch. `have 90 lakh feature and 50lakh(filtered dictionary).` doesn't make sense: you should have one dictionary, and use that consistently everywhere. You shouldn't be using two dictionaries (~two vectorization processes) at the same time.

I'm closing this but if you provide a reproducible example that shows that this is really a Gensim error (as opposed to dictionary mismatch) we can reopen and have a look.

**Closed by piskvorky** 2019-09-09 14:53 UTC
