### ISSUE TITLE
mycorpus.txt gies 404

### ISSUE THREAD

**Issue by raffaem** [RaRe-Technologies/gensim#3164] opened 2021-06-06 10:14 UTC
The link:

https://radimrehurek.com/gensim/auto_examples/core/mycorpus.txt

provided [here](https://radimrehurek.com/gensim/auto_examples/core/run_corpora_and_vector_spaces.html) returns a 404 error

**Comment by piskvorky** [comment] 2021-06-06 10:18
Thanks for reporting! Duplicate of #2872.

**Closed by piskvorky** 2021-06-06 10:18 UTC
