### ISSUE TITLE
fasttext: KeyError raised for OOV words in predict_output_word

### ISSUE THREAD

**Issue by morkiid** [RaRe-Technologies/gensim#3186] opened 2021-07-02 11:49 UTC
`predict_output_word` with fasttext model behaviour on OOV words is not consistent with word2vec, since `w in self.wv` always returns `True` for fasttext.

```python
----> 1 model.predict_output_word(['a'])

~gensim\models\word2vec.py in predict_output_word(self, context_words_list, topn)
   1820             raise RuntimeError("Parameters required for predicting the output words not found.")
   1821 
-> 1822         word2_indices = [self.wv.get_index(w) for w in context_words_list if w in self.wv]
   1823         if not word2_indices:
   1824             logger.warning("All the input context words are out-of-vocabulary for the current model.")

~gensim\models\word2vec.py in <listcomp>(.0)
   1820             raise RuntimeError("Parameters required for predicting the output words not found.")
   1821 
-> 1822         word2_indices = [self.wv.get_index(w) for w in context_words_list if w in self.wv]
   1823         if not word2_indices:
   1824             logger.warning("All the input context words are out-of-vocabulary for the current model.")

~gensim\models\keyedvectors.py in get_index(self, key, default)
    394             return default
    395         else:
--> 396             raise KeyError(f"Key '{key}' not present")
    397 
    398     def get_vector(self, key, norm=False):

KeyError: "Key 'a' not present"
```

#### Versions

```python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
Bits 64
NumPy 1.20.2
SciPy 1.6.2
gensim 4.0.1
FAST_VERSION 1
```

**Comment by piskvorky** [comment] 2021-07-02 12:03
Correct. This is intended behaviour.

Closing here but let me know if you see a bug somewhere. Be sure to include a minimal reproducing example + motivating description of the reported bug.

**Closed by piskvorky** 2021-07-02 12:03 UTC
