### ISSUE TITLE
Mistake in tutorial code

### ISSUE THREAD

**Issue by iwolford** [RaRe-Technologies/gensim#2736] opened 2020-01-26 18:10 UTC
Tutorial: Similarity Queries
https://radimrehurek.com/gensim/auto_examples/core/run_similarity_queries.html#sphx-glr-auto-examples-core-run-similarity-queries-py

Notice the document order in the tutorial:
```
documents = [
    "Human machine interface for lab abc computer applications",
    "A survey of user opinion of computer system response time",
    "The EPS user interface management system",
    "System and human system engineering testing of EPS",
```

Current snippet in the tutorial prints text in the original documents order, not the actual associated text. 
```
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims):
    print(s, documents[i])

Out:
(2, 0.9984453) Human machine interface for lab abc computer applications
(0, 0.998093) A survey of user opinion of computer system response time
(3, 0.9865886) The EPS user interface management system
(1, 0.93748635) System and human system engineering testing of EPS
```

The code should be
```
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for s in sims:
    print(s, documents[s[0]])

Out:
(2, 0.9984453) The EPS user interface management system
(0, 0.998093) Human machine interface for lab abc computer applications
(3, 0.9865886) System and human system engineering testing of EPS
(1, 0.93748635) A survey of user opinion of computer system response time
```

**Comment by piskvorky** [comment] 2020-01-26 18:49
You're right. Duplicate of #2699

**Comment by Akashtyagi08** [comment] 2020-03-03 18:54
How can I contribute on this ?

**Closed** 2020-03-05 00:33 UTC
Labels: documentation, easy
