### ISSUE TITLE
assert self.projection.u is not None, "decomposition not initialized yet"

### ISSUE THREAD

**Issue by Golnoush123** [RaRe-Technologies/gensim#2278] opened 2018-11-24 15:33 UTC
I aim to implement lsa similarity based on wikipedia to find the similarity among my questions and answers. I wrote the coed below but it gives me this error recently when I started run it on hpc. Any helpis appreciated. I do not get any error when run this program on my pc with the same version of gensim 3.4.0

`# load the corpora created in the previous notebook
tfidf_corpus = gensim.corpora.MmCorpus('./data/wiki_tfidf.mm')
lsi_corpus = gensim.corpora.MmCorpus('./data/wiki_lsa.mm')
#print(tfidf_corpus)
#print(lsi_corpus)

# load the models too
id2word_wiki = gensim.corpora.Dictionary.load('./data/wiki.dictionary')
#lda_model = gensim.models.LdaModel.load('./data/lda_wiki.model')
tfidf_model = gensim.models.TfidfModel.load('./data/tfidf_wiki.model')
lsi_model = gensim.models.LsiModel.load('./data/lsi_wiki.model')

index = Similarity('./data/wiki_index', lsi_corpus, num_features=lsi_corpus.num_terms)
#print(index)

# store to disk
index.save('./data/wiki_index.index')

# load back = same index
index = Similarity.load('./data/wiki_index.index')
#print(index)
 docs_bow = (id2word.doc2bow(tokenize(document)) for document in index_documents)
 docs_tfidf = tfidf_model[docs_bow]
 docs_lsi = lsi_model[docs_tfidf]`

error:
  File "lsa-final1.py", line 226, in <module>
    docs_lsi = lsi_model[docs_tfidf]
  File "/root/anaconda3/envs/my_env/lib/python3.7/site-packages/gensim/models/lsimodel.py", line 564, in __getitem__
    assert self.projection.u is not None, "decomposition not initialized yet"
AttributeError: 'NoneType' object has no attribute 'u'

**Comment by menshikh-iv** [comment] 2018-12-13 17:35
Hi @Golnoush123, looks a bit suspicious, can you please share all the models that mentioned in your post, please? I need to reproduce your issue first.

**Comment by menshikh-iv** [comment] 2019-01-14 03:17
closing (lack of information, unreproducible)

**Closed by menshikh-iv** 2019-01-14 03:17 UTC
Labels: need info

**Comment by mark-todd** [comment] 2021-11-17 12:38
So I am also receiving this error - but the good news is I have a working minimal example that replicates it. It seems to be more an error handling issue than anything, as it requires you to set the input to dictionary to the empty list (which is invalid syntax).
```
from gensim import corpora, models, similarities

texts = []
dictionary = corpora.Dictionary(texts)
corpus = []
lsi = models.LsiModel(corpus, id2word=dictionary, num_topics=2)
index = similarities.MatrixSimilarity(lsi[corpus])
```

**Comment by mark-todd** [comment] 2021-11-17 12:45
Could we potentially reopen this? @menshikh-iv
