### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xef

### ISSUE THREAD

**Issue by ABUAMEER23** [RaRe-Technologies/gensim#3417] opened 2022-12-17 11:40 UTC
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
print(my_model.lifecycle_events)
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by mpenkov** [comment] 2022-12-17 12:59
Your example is not reproducible. Please either provide the model, or a way to build a model that reproduces the bug.

Otherwise, we cannot help you.

**Comment by gojomo** [comment] 2022-12-28 19:20
Closing for lack of details. Could reopen with sufficient details to reproduce an error, but is probably some form of user error, like trying to unpickle/load the wrong kind of file, or a corrupted/damaged file.

**Closed by gojomo** 2022-12-28 19:20 UTC
Labels: need info

**Comment by JohannesSigbjorn** [comment] 2023-05-17 08:26
I have the same error.
I was trying to load LDA model.
`lda_model=gensim.models.ldamodel.LdaModel.load(fname='ldamodel.html')`
I think the problem is that model has Russian language in it, and in pickle.load has `latin1` encoding 
>`return _pickle.load(f, encoding='latin1')`

Here is model:
[ldamodel.zip](https://github.com/RaRe-Technologies/gensim/files/11495654/ldamodel.zip)

Here is full error:
```
UnpicklingError                           Traceback (most recent call last)
Cell In [231], line 1
----> 1 lda_model=gensim.models.ldamodel.LdaModel.load(fname='ldamodel.html')

File ~/anaconda3/envs/vishnyakov/lib/python3.8/site-packages/gensim/models/ldamodel.py:1663, in LdaModel.load(cls, fname, *args, **kwargs)
   1634 """Load a previously saved :class:`gensim.models.ldamodel.LdaModel` from file.
   1635 
   1636 See Also
   (...)
   1660 
   1661 """
   1662 kwargs['mmap'] = kwargs.get('mmap', None)
-> 1663 result = super(LdaModel, cls).load(fname, *args, **kwargs)
   1665 # check if `random_state` attribute has been set after main pickle load
   1666 # if set -> the model to be loaded was saved using a >= 0.13.2 version of Gensim
   1667 # if not set -> the model to be loaded was saved using a < 0.13.2 version of Gensim,
   1668 # so set `random_state` as the default value
   1669 if not hasattr(result, 'random_state'):

File ~/anaconda3/envs/vishnyakov/lib/python3.8/site-packages/gensim/utils.py:486, in SaveLoad.load(cls, fname, mmap)
    482 logger.info("loading %s object from %s", cls.__name__, fname)
    484 compress, subname = SaveLoad._adapt_by_suffix(fname)
--> 486 obj = unpickle(fname)
    487 obj._load_specials(fname, mmap, compress, subname)
    488 obj.add_lifecycle_event("loaded", fname=fname)

File ~/anaconda3/envs/vishnyakov/lib/python3.8/site-packages/gensim/utils.py:1461, in unpickle(fname)
   1447 """Load object from `fname`, using smart_open so that `fname` can be on S3, HDFS, compressed etc.
   1448 
   1449 Parameters
   (...)
   1458 
   1459 """
   1460 with open(fname, 'rb') as f:
-> 1461     return _pickle.load(f, encoding='latin1')

UnpicklingError: invalid load key, '\x0a'.
```

**Comment by JohannesSigbjorn** [comment] 2023-05-17 13:35
Oh, and i was dumb, i was trying to open visualized model from pyLDAvis instead of actual model from lda. So my above message is pointless.
