### ISSUE TITLE
Word Embedding Models loaded through gensim.downloader crash when used in Celery Tasks

### ISSUE THREAD

**Issue by pmbaumgartner** [RaRe-Technologies/gensim#2018] opened 2018-04-05 21:58 UTC
#### Description
After loading models with the `gensim.downloader` api, using methods in a Celery task causes the worker to crash and the task to fail.

When running the function normally (not as a task), the function gives expected results.

When loading in models through `KeyedVectors.load_word2vec_format()`, the task executes without issue, both when using the original source files and the ones downloaded from the `gensim.downloader` api.

Possibly related: https://github.com/RaRe-Technologies/gensim/issues/1293

#### Steps/Code/Corpus to Reproduce

I've created a [gist](https://gist.github.com/pmbaumgartner/7b5d8d08392b21816c90e189c78277b4) with the relevant files to reproduce. There are 3 relevant files. 

- `tasks.py` contains the tasks and the model loading code. Currently loading models is commented out to test loading only one specific model at a time.
- `run.py` is generic code that is used to run the tasks.
- `Procfile` is used to run the redis-server and celery worker using [honcho](https://honcho.readthedocs.io/en/latest/index.html).

To run celery and redis with the Procfile and honcho, use `honcho start` from the shell.

After redis and celery are up, we can run the tasks. When running the task with one of the non-working models from the `gensim.downloder` api, the following occurs when attempting to run the task:

```
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,697: INFO/MainProcess] Received task: tasks.most_sim[ab7aa3af-1b10-462f-accb-9c269d8eda2f]
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,700: WARNING/ForkPoolWorker-7] hello
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,703: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:1734 exited with 'signal 11 (SIGSEGV)'
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,721: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
17:43:24 celery_worker.1 | Traceback (most recent call last):
17:43:24 celery_worker.1 |   File "/Users/pbaumgartner/anaconda3/envs/celery-nlp/lib/python3.6/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
17:43:24 celery_worker.1 |     human_status(exitcode)),
17:43:24 celery_worker.1 | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

#### Expected Results
When the task completes regularly, I am able to retrieve the result and I see the following from the celery worker:

```
17:40:59 celery_worker.1 | [2018-04-05 17:40:59,879: INFO/MainProcess] Received task: tasks.most_sim[8096ab3a-de4a-45d2-8814-cc4c2bfe15d0]
17:40:59 celery_worker.1 | [2018-04-05 17:40:59,881: WARNING/ForkPoolWorker-8] hello
17:40:59 celery_worker.1 | [2018-04-05 17:40:59,910: INFO/ForkPoolWorker-8] Task tasks.most_sim[8096ab3a-de4a-45d2-8814-cc4c2bfe15d0] succeeded in 0.030041170000913553s: [('dog', 0.9218006134033203), ('rabbit', 0.8487820625305176), ('monkey', 0.8041081428527832), ('rat', 0.7891963124275208), ('cats', 0.7865269780158997), ('snake', 0.7798910140991211), ('dogs', 0.7795814871788025), ('pet', 0.7792249917984009), ('mouse', 0.773166835308075), ('bite', 0.7728800177574158)]
```

#### Actual Results
```
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,697: INFO/MainProcess] Received task: tasks.most_sim[ab7aa3af-1b10-462f-accb-9c269d8eda2f]
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,700: WARNING/ForkPoolWorker-7] hello
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,703: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:1734 exited with 'signal 11 (SIGSEGV)'
17:43:24 celery_worker.1 | [2018-04-05 17:43:24,721: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
17:43:24 celery_worker.1 | Traceback (most recent call last):
17:43:24 celery_worker.1 |   File "/Users/pbaumgartner/anaconda3/envs/celery-nlp/lib/python3.6/site-packages/billiard/pool.py", line 1223, in mark_as_worker_lost
17:43:24 celery_worker.1 |     human_status(exitcode)),
17:43:24 celery_worker.1 | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

#### Versions
```python
>>> import platform; print(platform.platform())
Darwin-17.4.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.0.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.4.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0
```

There is also a `requirements.txt` file in the gist.

**Comment by menshikh-iv** [comment] 2018-04-06 04:58
Thanks for the detailed description @pmbaumgartner, I'll try to reproduce it.
IMO looks like a wired side-effect (but why, I see no reasons now how SIGSEGV can be produced here).

**Comment by menshikh-iv** [comment] 2018-04-06 07:34
@pmbaumgartner try to make the same with standard python interpreter (not anaconda)

I checked both `google-news` & `gigaword-50` mentioned as "broken" in your code, but all works as expected (with celery pipeline). Unfortunately, the issue isn't reproducible, for this reason, I close it.

**Closed by menshikh-iv** 2018-04-06 07:34 UTC

**Comment by piskvorky** [comment] 2018-04-06 07:58
Yes, I remember Anaconda had issues in the past (badly compiled BLAS, NumPy -- nothing to do with Gensim). Please try with a standard CPython interpreter and let us know if that solves the issue.
