### ISSUE TITLE
Error while loading French binary model

### ISSUE THREAD

**Issue by qdHe** [RaRe-Technologies/gensim#2529] opened 2019-06-15 01:06 UTC
I download pretrained fasttext models of English and French from https://fasttext.cc/docs/en/pretrained-vectors.html. When I use load_facebook_model() function to load the data, `wiki.en.bin` goes well but `wiki.fr.bin` cannot be loaded. The error is 
```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/home/qihe/r-1694068/build/scsar-word-embeddings/venv/lib/python3.6/site-packages/gensim/models/fasttext.py", line 1299, in l
oad_facebook_vectors
   model_wrapper = _load_fasttext_format(path, encoding=encoding, full_model=False)
 File "/home/qihe/r-1694068/build/scsar-word-embeddings/venv/lib/python3.6/site-packages/gensim/models/fasttext.py", line 1323, in _
load_fasttext_format
   m = gensim.models._fasttext_bin.load(fin, encoding=encoding, full_model=full_model)
 File "/home/qihe/r-1694068/build/scsar-word-embeddings/venv/lib/python3.6/site-packages/gensim/models/_fasttext_bin.py", line 271,
in load
   raw_vocab, vocab_size, nwords = _load_vocab(fin, new_format, encoding=encoding)
 File "/home/qihe/r-1694068/build/scsar-word-embeddings/venv/lib/python3.6/site-packages/gensim/models/_fasttext_bin.py", line 167,
in _load_vocab
   raise NotImplementedError("Supervised fastText models are not supported")
NotImplementedError: Supervised fastText models are not supported
```
I do not think only the French model is supervised. Is there any bug? If it is not a bug in gensim, I guess there is some problem in the model. With a closer look, I find that the value of `nwords` and the size of vocabulary is 1152450, while the size of vectors  is 1152449. I am not sure what is the reason of this mismatch. @cpuhrsch

System: RHEL 7
Gensim: 3.7.2

Some related issue: https://github.com/facebookresearch/fastText/issues/218

**Comment by mpenkov** [comment] 2019-07-07 09:15
Please provide sample source code to reproduce your issue.

**Comment by cpuhrsch** [comment] 2019-07-08 22:05
@qdHe - I am not working on fastText anymore, please refer to the current maintainers possibly based on recent commits over at the main repository.

**Comment by mpenkov** [comment] 2019-09-28 22:52
Closing due to lack of information from author.

**Closed by mpenkov** 2019-09-28 22:52 UTC
Labels: need info
