### ISSUE TITLE
Potential numerical instability in word2vec scoring functions?

### ISSUE THREAD

**Issue by jmhessel** [RaRe-Technologies/gensim#1472] opened 2017-07-06 21:28 UTC
Hi there --

I figured I'd file a separate issue to go along with my observations in #999 but I think there is a numerical instability when comparing the model scoring between numpy and cython in word2vec. I discovered this instability when implementing scoring functions for doc2vec in my fork of gensim. After much debugging, I discovered the following:

Numpy uses `logaddexp` to score pairs for cbow and skipgram ([the documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp.html) mentions that this function takes special precautions for numerical stability reasons), i.e.,

```
def score_sg_pair(model, word, word2):
    l1 = model.wv.syn0[word2.index]
    l2a = deepcopy(model.syn1[word.point])  # 2d matrix, codelen x layer1_size
    sgn = (-1.0)**word.code  # ch function, 0-> 1, 1 -> -1
    lprob = -logaddexp(0, -sgn * dot(l1, l2a.T))
    return sum(lprob)


def score_cbow_pair(model, word, l1):
    l2a = model.syn1[word.point]  # 2d matrix, codelen x layer1_size
    sgn = (-1.0)**word.code  # ch function, 0-> 1, 1 -> -1
    lprob = -logaddexp(0, -sgn * dot(l1, l2a.T))
    return sum(lprob)
```
note that this implicitly computes the log of the sigmoid function for each internal node of the hierarchical softmax -- i.e.,
```
-logaddexp(0, -y)
-logadd(1, e^-y)
-log(1+e^-y)
log ( 1 / (1 + e^-y))
```
the cython implementations use a different method, which I think is mathematically equivalent, i.e. it explicitly computes the log sigmoids in a table first, and then sums them up. https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec_inner.pyx#L672-L680

```
for b in range(codelens[i]):
    row2 = word_point[b] * size
    f = our_dot(&size, neu1, &ONE, &syn1[row2], &ONE)
    sgn = (-1)**word_code[b] # ch function: 0-> 1, 1 -> -1
    f = sgn*f
    if f <= -MAX_EXP or f >= MAX_EXP:
       continue
    f = LOG_TABLE[<int>((f + MAX_EXP) * (EXP_TABLE_SIZE / MAX_EXP / 2))]
    work[0] += f
```
`LOG_TABLE` contains precomputed `log(sigmoid(x))`.

I can't quite pinpoint where these two implementations differ (they differ even when the `MAX_EXP` check doesn't fire), but I have found that they can produce significantly different outputs, even when I increase the resolution of the `LOG_TABLE.` When I use a more numerically stable logaddexp in cython, the output matches the numpy output. I will be doing a bit more investigation but figured I'd mention this.

Also, in my branch, I added functions that do model scoring for doc2vec, if those are of interest.

**Comment by menshikh-iv** [comment] 2017-08-14 10:48
Hi @jmhessel,
Feel free to contribute, scoring function for d2v is a nice feature!
@chinmayapancholi13 @gojomo what's do you think about this "instability"?

**Comment by gojomo** [comment] 2017-08-14 19:12
I'm not sure what 'instability' means in this context - is it a matter of different orders-of-operations among ought-to-be-idenitical calculations making a big final difference because of floating-point precision limitations? I'd want a specific example of differences (and differences mattering) to comment further.

**Comment by jmhessel** [comment] 2017-08-14 20:07
Yes -- that's exactly what I mean in terms of instability; these two calculations should produce the same value, but differ beyond numerical precision to the point where the differences were impacting some of my use-cases. I can provide some specific examples ASAP, along with cleaned-up versions of the paragraph vector scoring functions, though I am swamped for the next few weeks.

**Comment by menshikh-iv** [comment] 2017-10-02 08:44
ping @jmhessel

**Comment by menshikh-iv** [comment] 2017-10-31 06:18
ping @jmhessel, please provide specific examples for us, because so far the problem is not clear.

**Comment by jmhessel** [comment] 2017-10-31 06:23
Sorry -- yes. This is on my todo list. My first todo will be to get paragraph vector scoring functions merged because that is where the issue first arose for me (I have these written in python/cython on my fork). Then, I will look back at this. I've been a bit swamped lately, but this is on my todos.

**Comment by menshikh-iv** [comment] 2018-02-09 06:36
@jmhessel ping, if you don't provide an example - I'll close this issue.

**Comment by menshikh-iv** [comment] 2018-02-16 06:47
This issue unreproducible without example, for this reason, I close this.

**Closed by menshikh-iv** 2018-02-16 06:47 UTC
Labels: bug, medium, need info
