### ISSUE TITLE
How do you avoid Garbage in garbage out?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [RaRe-Technologies/gensim#1609] opened 2017-10-03 18:36 UTC
How do you plan out your program that uses gensim? Which questions do you ask yourself to tokenize properly and get usable results? How do you avoid Garbage in garbage out?

**Comment by gojomo** [comment] 2017-10-03 19:09
This issue-tracker is for bugs & feature-requests. A better place to ask open-ended questions is the discussion list, and I see you've already asked the same question there (https://groups.google.com/forum/#!topic/gensim/mNhWhlmMJbk), so closing this issue.

**Closed by gojomo** 2017-10-03 19:09 UTC

**Comment by ErfolgreichCharismatisch** [comment] 2017-10-03 20:19
Yes and nobody is answering there as always on google groups. This is why I posted here.

**Comment by gojomo** [comment] 2017-10-03 21:23
You asked on the list a mere 4 hours ago; I would suggest waiting 48 hours (or more) before having any concern that a question won't get an answer, and thus taking extra steps to repeat it elsewhere (in less appropriate forums). Most questions on the gensim forum, especially specifically about gensim itself, get answers. 

Your question might not get a great answer, because it is extremely generic and open-ended.  Tokenization choices vary a lot, and aren't specific to gensim. You haven't mentioned your dataset/language or goals. Without such details, you're essentially asking for a free-form education on a large topic, not support for a specific problem/task. Such an education would be best found by searching online for articles & tutorials, and working through examples to develop a sense of what others commonly do in different situations. Good luck!

**Comment by ErfolgreichCharismatisch** [comment] 2017-10-03 21:29
> You haven't mentioned your dataset/language or goals. 

My goal is to have a set of pdf files indexed in a corpus such that using the similarity search it would output the most fitting paragraphs in the most fitting pdfs without necessarily containing the same words in the paragraphs and the search term or phrase(which gensim is famous for).

**Comment by gojomo** [comment] 2017-10-03 21:35
That's helpful extra context! But this is still the wrong place to discuss, if it's not a bug or feature-request.

**Comment by ErfolgreichCharismatisch** [comment] 2017-10-03 21:39
Can you answer here https://groups.google.com/forum/#!topic/gensim/Lnz3LxDZwMI

**Comment by gojomo** [comment] 2017-10-03 21:46
I won't be, but if you wait the recommended 48+ hours, and if you don't get a reply continue to improve the question with more details that make it specific enough to answer, you might get helpful replies there.

**Comment by ErfolgreichCharismatisch** [comment] 2017-10-03 23:49
> I won't be

Why?

**Comment by gojomo** [comment] 2017-10-04 02:22
> Why?

It's still too open-ended, and doesn't match topics where I enjoy writing answers, and I have lots of other higher-priority interests! Good luck!
