### ISSUE TITLE
All the vocab model files are not saved 

### ISSUE THREAD

**Issue by Swty13** [RaRe-Technologies/gensim#3277] opened 2021-12-08 04:57 UTC
#### Problem description

I am trying to build vocab model using Doc2Vec Model. 
As file is very large near 14-15GB I m expecting 4 files related to vocab (M running this on Server)
 1. vocab_model.wv.vectors.npy
 2. vocab_model.trainables.syn1neg.npy
 3. vocab_model.docvecs.vectors_docs.npy
 4. vocab_model
But only three files are generated
 1. vocab_model.wv.vectors.npy
 2. vocab_model.trainables.syn1neg.npy
 3. vocab_model.docvecs.vectors_docs.npy
But when I run same on my local server all 4 files are generated.

#### Steps
Gensim model: Doc2Vec
finalSent : Text for building vocabulary 
new_path: path for storing vocab related files
Following is code for replicate:
```
def build_vocabulary(finalSent, new_path):
    try:
        save_model = "vocab_model"  # ("enter name of the model: ")

        modelDoc = Doc2Vec(size=300, window=5, dm=0, dbow_words=1, hs=0, negative=10, alpha=0.05, min_count=20,
                           workers=cores, sample=1e-5, seed=0, iter=10)
        print("model loaded successfully")
        modelDoc.build_vocab(finalSent)
        print("modelDoc.build_vocab runs successfully")
        if not os.path.exists(new_path):
            os.makedirs(new_path)
        modelDoc.save(new_path + "%s" % save_model)
        print(" Vocab Model Name is !!!" + str(new_path + "%s" % save_model))

        print("Vocab Model Build Successfully!!!")
    except Exception as e:
        print(" Error in Vocab Model!!!" + str(e))
```
## Output:
```
 print("model loaded successfully")
 print("modelDoc.build_vocab runs successfully")
```
There is no error in exception .Code just terminated after build vocab. I could not understand the error.Is there any code issue or environmental issue(as code running in my local server so may be there is no issue in code I am not sure🤔 )

#### Versions
```
scipy==1.2.0
gensim==0.12.2
```
Thanks in advance.

**Comment by piskvorky** [comment] 2021-12-08 09:18
Gensim 0.12.2 is over 6 years old. While it's great such ancient code still runs, it's definitely not something we support :)

The latest version of Gensim is 4.1.2 – please upgrade.

**Comment by Swty13** [comment] 2021-12-08 16:53
Thanks to the Gensim library this old version code still runs perfectly on our servers.

Sure I will update version.

**Comment by piskvorky** [comment] 2021-12-08 17:55
@gojomo does the problem description ring any bell?

**Comment by gojomo** [comment] 2021-12-08 19:48
Nope. But from description, sounds like some sort of crash, maybe memory-exhaustion-related, *after* the subsidiary arrays are written but *before* the outermost model (pickle) object is saved. If diagnosing were a priority, adding max logging, and watching the console, through a failure would probably provide more info. (Depending on things like Python version, might even just be hitting some pickle implementation limit, if for example vocabulary is gigantic - though I suppose if 300d vectors already written vocab can't be that larger. With a config that old, maybe even a 32bit Python interpreter is involved?)

**Comment by Swty13** [comment] 2021-12-09 03:42
Python interpreter -64bit.
Python version- 3.6.5
I also put logs and exception but code stuck/out  before this line print(" Vocab Model Name is !!!" + str(new_path + "%s" % save_model)) . I mean this line is not displaying on log file.
At the output folder file size are:
1. vocab_model.wv.vectors.npy.    --- 132MB
2. vocab_model.trainables.syn1neg.npy --- 132 MB
3. vocab_model.docvecs.vectors_docs.npy --- 5.71 GB
4. vocab_model.                                              --0 B

Vocab model size is 0B that's why my job fails every time.

**Comment by gojomo** [comment] 2021-12-09 06:21
If it doesn't reproduce in gensim-4.1.2, whatever particular thing might be going wrong isn't likely to be of interest, whatever the cause. 

I also don't see anything in this report that resembles what logging output of INFO level should look like, or what true console/stdout output might look like. (Even the info labeled "Output:" is clearly not the actual result of the debug `print()` calls, but the lines of code themselves, as if cut & pasted to roughly simulate output. If actually debugging the situation involving the old code, real logging/console output would bea necessary clue to what's happening.)

**Comment by Swty13** [comment] 2021-12-09 16:37
Hi @gojomo 
From last so many years I am using this version Doc2vec model on <14GB data it was absolutely running fine all the vocab related files generated properly.
This issue arises when the data size increase to 16-16.5GB. 
I was debugging this issue and try to replicate on different server and face same problem  with same version so this is not issue of Memory/CPU.
Solution till now is I will surely migrate my code to upgraded version.

Just one thing I want to know regarding above problem that is there any constraint in gensim library that it can't save such a huge data when it save files in pickle.
For less amount of data it only create one vocab file but when data is huge it create multiple vocab files and that's absolutely fine.I am not sure about this that how those files are divided but it divide whole vocabulary file in chunks files. Is there any kind of limitation in "save" function when data is huge.

#### save definition from gensim/utils.py

```
    def save(
            self, fname_or_handle,
            separately=None, sep_limit=10 * 1024 ** 2, ignore=frozenset(), pickle_protocol=PICKLE_PROTOCOL,
    ):
        self.add_lifecycle_event(
            "saving",
            fname_or_handle=str(fname_or_handle),
            separately=str(separately),
            sep_limit=sep_limit,
            ignore=ignore,
        )
        try:
            _pickle.dump(self, fname_or_handle, protocol=pickle_protocol)
            logger.info("saved %s object", self.__class__.__name__)
        except TypeError:  # `fname_or_handle` does not have write attribute
            self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)

```

Thanks.

**Comment by gojomo** [comment] 2021-12-30 22:52
Closing as there seems nothing left to debug/resolve here - but feel free to follwup if there is.

**Closed by gojomo** 2021-12-30 22:52 UTC
