### ISSUE TITLE
Error executing gensim_news_classification.ipynb 

### ISSUE THREAD

**Issue by mon95** [RaRe-Technologies/gensim#958] opened 2016-10-17 20:28 UTC
gensim_news_classification.ipynb throws the following error while running the following cell under "Topic Modelling using LDA"
```pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)```

```TypeError: cannot sort an Index object in-place, use sort_values instead```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-eb5f7004bc08> in <module>()
----> 1 pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

/home/ssreehari10/anaconda2/envs/gensim1/lib/python2.7/site-packages/pyLDAvis/gensim.pyc in prepare(topic_model, corpus, dictionary, doc_topic_dist, **kwargs)
    108     """
    109     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
--> 110     return vis_prepare(**opts)

/home/ssreehari10/anaconda2/envs/gensim1/lib/python2.7/site-packages/pyLDAvis/_prepare.pyc in prepare(topic_term_dists, doc_topic_dists, doc_lengths, vocab, term_frequency, R, lambda_step, mds, n_jobs, plot_opts, sort_topics)
    396 
    397    topic_info         = _topic_info(topic_term_dists, topic_proportion, term_frequency, term_topic_freq, vocab, lambda_step, R, n_jobs)
--> 398    token_table        = _token_table(topic_info, term_topic_freq, vocab, term_frequency)
    399    topic_coordinates = _topic_coordinates(mds, topic_term_dists, topic_proportion)
    400    client_topic_order = [x + 1 for x in topic_order]

/home/ssreehari10/anaconda2/envs/gensim1/lib/python2.7/site-packages/pyLDAvis/_prepare.pyc in _token_table(topic_info, term_topic_freq, vocab, term_frequency)
    265    # term-topic frequency table of unique terms across all topics and all values of lambda
    266    term_ix = topic_info.index.unique()
--> 267    term_ix.sort()
    268    top_topic_terms_freq = term_topic_freq[term_ix]
    269    # use the new ordering for the topics

/home/ssreehari10/anaconda2/envs/gensim1/lib/python2.7/site-packages/pandas/indexes/base.pyc in sort(self, *args, **kwargs)
   1701 
   1702     def sort(self, *args, **kwargs):
-> 1703         raise TypeError("cannot sort an Index object in-place, use "
   1704                         "sort_values instead")
   1705 

TypeError: cannot sort an Index object in-place, use sort_values instead
```

**Comment by tmylk** [comment] 2016-10-18 12:29
Ping @dsquareindia

**Comment by dsquareindia** [comment] 2016-10-25 07:03
This seems to be a problem with pyLDAvis. @mon95 can you please post which version of pyLDAvis you're using?

**Comment by dsquareindia** [comment] 2016-10-25 07:22
Sorry but I'm not able to reproduce this error on my machine. Could you please elaborate on how you got this error?

**Comment by mon95** [comment] 2016-10-25 08:22
I'm using version pyldavis 2.0.0. 

Also, I'm using a python2.7 kernel. Could you check using python2.7? I found this while testing the ipython notebook files. 

Using "Restart and run all cells" while working with the Jupyter Notebook should show this error.

**Comment by dsquareindia** [comment] 2016-10-25 08:42
Oh even I did the same thing using the same versions. Strange.... Will look into this.

**Comment by mon95** [comment] 2016-10-26 16:50
There seems to be a similar issue which may/may not have been resolved completely here [https://github.com/bmabey/pyLDAvis/issues/74](url). And, this is not part of the 2.0.0 release. 

Still not sure why the error shows up though.

**Comment by mon95** [comment] 2016-10-27 18:18
A similar error has been reported here - https://github.com/bmabey/pyLDAvis/issues/74. 
But the fix isn't part of the latest release. Any thoughts? Or should we ignore this for now?

**Comment by dsquareindia** [comment] 2016-10-27 18:41
It's strange because I'm not able to reproduce this error. Which version of pandas are you using?

**Comment by mon95** [comment] 2016-10-27 19:26
I'm using pandas 0.19.0. 

Also, while testing using python3.5, the cell(s) dependent on Pattern fail because, there's no support for python3 yet.

**Comment by tmylk** [comment] 2016-10-28 07:57
This issue should really be raised in pyLDAVis repo. Will close it here if you agree.

**Comment by mon95** [comment] 2016-10-28 08:03
@tmylk Yes, I agree.

**Comment by dsquareindia** [comment] 2016-10-28 08:38
hmmm I use pandas version 0.18.1. Yeah you should probably raise this in the pyLDAvis repo and suggest the `np.sort()` fix there if it's working for you. That would really help.

**Closed** 2016-10-28 14:52 UTC
Labels: bug, documentation

**Comment by tmylk** [comment] 2016-11-08 08:48
The issue is with PyLDAVis incompatibility with pandas 0.19. To be fixed in next PyLDAVis release.
As explained in https://github.com/bmabey/pyLDAvis/issues/76 and reproduced by @dsquareindia above
