### ISSUE TITLE
random slice of mm corpus broken on conda?

### ISSUE THREAD

**Issue by mattilyra** [RaRe-Technologies/gensim#1046] opened 2016-12-14 16:17 UTC
I think there's an issue with the `conda` package of 13.3 - I can't take a random slice of an `mm` corpus

    corpus = gensim.corpora.MmCorpus('./corpus.mm')
    corpus[np.asarray([4, 10, 3, 16])]

fails with an error

> gensim/matutils.py in docbyoffset(self, offset)
    677         previd, document = -1, []
    678         for line in fin:
--> 679             docid, termid, val = line.split()
    680             if not self.transposed:
    681                 termid, docid = docid, termid
ValueError: not enough values to unpack (expected 3, got 2)

Installing straight from github using `pip install` this problem goes away. Can anyone confirm this issue?

Using Ubuntu 16.04 and Python 3.5

**Comment by souravsingh** [comment] 2016-12-18 18:12
I think the conda recipe for Gensim is quite old and hasn't been maintained for quite some time. We are looking to push the recipe though conda-forge channel, which should help in maintainance.

**Comment by tmylk** [comment] 2017-01-20 22:39
Closing as duplicate of https://github.com/RaRe-Technologies/gensim/issues/892

**Closed by tmylk** 2017-01-20 22:39 UTC
Labels: bug
