### ISSUE TITLE
save_facebook_model() - AssertionError

### ISSUE THREAD

**Issue by imendibo** [RaRe-Technologies/gensim#2853] opened 2020-06-10 20:21 UTC
#### Problem description
I am trying to save the trained model of fasttext using the new save_facebook_model function.
I was unable to do it so because an assertionError arises in the code line:
`assert vocab_n == len(model.wv.vocab)`
 The vocabulary of my model is of 2000264:
```
len(model.wv.vocab)
2000264
```
I tried with a model with a vocabulary of 4500 and it worked. So I guess there is a limitation in that. But the error message did not tell any of that.

#### Steps/code/corpus to reproduce

```
from gensim.models.fasttext import save_facebook_model

save_facebook_model(model,'own_fasttext_model_pretrained.bin')

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-201-0a3c1c458b74> in <module>
      2 from gensim.models.fasttext import load_facebook_model, load_facebook_vectors,save_facebook_model
      3 
----> 4 save_facebook_model(model,'own_fasttext_model_pretrained.bin')

/opt/conda/lib/python3.7/site-packages/gensim/models/fasttext.py in save_facebook_model(model, path, encoding, lr_update_rate, word_ngrams)
   1334     """
   1335     fb_fasttext_parameters = {"lr_update_rate": lr_update_rate, "word_ngrams": word_ngrams}
-> 1336     gensim.models._fasttext_bin.save(model, path, fb_fasttext_parameters, encoding)

/opt/conda/lib/python3.7/site-packages/gensim/models/_fasttext_bin.py in save(model, fout, fb_fasttext_parameters, encoding)
    666     if isinstance(fout, str):
    667         with open(fout, "wb") as fout_stream:
--> 668             _save_to_stream(model, fout_stream, fb_fasttext_parameters, encoding)
    669     else:
    670         _save_to_stream(model, fout, fb_fasttext_parameters, encoding)

/opt/conda/lib/python3.7/site-packages/gensim/models/_fasttext_bin.py in _save_to_stream(model, fout, fb_fasttext_parameters, encoding)
    629 
    630     # Save words and ngrams vectors
--> 631     _input_save(fout, model)
    632     fout.write(struct.pack('@?', False))  # Save 'quot_', which is False for unsupervised models
    633 

/opt/conda/lib/python3.7/site-packages/gensim/models/_fasttext_bin.py in _input_save(fout, model)
    573 
    574     assert vocab_dim == ngrams_dim
--> 575     assert vocab_n == len(model.wv.vocab)
    576     assert ngrams_n == model.wv.bucket
    577 

AssertionError: 
```

#### Versions

```
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Linux-4.9.0-12-amd64-x86_64-with-debian-9.12
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0]
NumPy 1.18.1
SciPy 1.4.1
gensim 3.8.3
FAST_VERSION 0
```

**Comment by mpenkov** [comment] 2020-06-10 23:21
Thank you for reporting this.

How did you train the model? We cannot reproduce the problem without it.

**Comment by gojomo** [comment] 2020-06-11 18:39
Yes - it's probably not just the size, but something about how that model was created/trained/modified. Knowing more about the steps it went through, in your code, would help – but best of all would be a complete standalone code example which can trigger the assertion error. 

(In any case, knowing that a mysterious failure of that assertion has happened "in the field", we could add a more descriptive failure message, with some of the relevant values, to narrow what kind of corruption occurred. For example, is the `len(vocab)` suspiciously small or the `vectors_vocab.shape[0]` suspiciously big?)

**Comment by imendibo** [comment] 2020-06-12 09:13
The model was created loading the facebook model cc.en.300.bin and training it with my own dataset of sentences:
```
from gensim.models.fasttext import load_facebook_model

model = load_facebook_model('fasttext/cc.en.300.bin')
model.build_vocab(sentences=list(df_train.desc_tokens_spacy), update = True)
model.train(sentences=list(df_train.desc_tokens_spacy), total_examples=len(df_train.desc_tokens_spacy), epochs=10) 

```

**Comment by gojomo** [comment] 2020-06-12 15:30
Thanks! What if you don't try any additional vocab-updates/training? That is, try the `.save_facebook_model()` immediately after the `load_facebook_model()`?

**Comment by imendibo** [comment] 2020-06-12 16:15
I just tried what you commented @gojomo and it saved the model that was just loaded. I have also extracted the length of the vocab and it was of 2000000.

**Comment by gojomo** [comment] 2020-06-12 18:02
That's very helpful, thanks - it suggests it is the vocab-expansion that causes the inconsistency. 

I suspect there might be other side-effects of this as well - the `FastText` class keeps both raw full-word vectors (as directly trained), and composed vectors (those raw full-words *plus* their constituent ngrams) - & this suggests vocab-expansion might not be updating both in sync. That could mean the word-vectors being used from other operations may be stale, and other operations might similarly hit some expected-size mismatch.

**Comment by piskvorky** [comment] 2020-07-26 16:04
@gojomo is this still the case?

Related to #2873, #2879.

**Comment by gojomo** [comment] 2020-07-27 04:49
I've never personally reproduced this, & don't know the real cause, so unsure of the likelihood of its persistence after other fixes.  (I'm not sure it necessarily even requires loading an FB-native model - *any* vocab-expansion via `build_vocab(... update=True)` *might* be enough... but there's not yet a compact standalone triggering case.) 

It might have been fixed by other refactoring... @imendibo, if you are comfortable installing & running the `develop` in-progress branch of Gensim, and you could try reproducing this there, that'd be a help. 

In case it's unclear, I'm not really a fan of the `build_vocab(..., update=True)` functionality, going back to its original arrival in #365 - it's never seemed completed (still segfaults in `Doc2Vec`), & makes something look sensible/supported that's actually very shaky in practice. I've never used it myself, & wouldn't encourage its use, so my time budget for fixing its problems is negligible. (My hunch would be that something based instead on the `TranslationMatrix` functionality would be a more-grounded & reliable way to expand vocabularies: train a new model on new data, but then translate the new words back into the old space, perhaps even with an explicit, tunable 'new-vs-old-relative-weight' parameter. Or maybe implement some well-described  'fine-tuning' idea that's written up in some research article. But I've not had a project or time to do that R&D.)

**Comment by piskvorky** [comment] 2020-09-07 14:56
@imendibo can you check with the current `develop`? We've fixed a bunch of stuff there.

**Comment by ClementViricel** [comment] 2020-09-11 09:35
Hello,
I have the same issue here with the update_vocab=True.
here the snipped : 
`model = gensim.models.fasttext.load_facebook_model("fasttext.bin")
model.build_vocab(corpus_file="data.txt", update=True)
model.train(
    corpus_file="data.txt", epochs=model.epochs,
    total_examples=model.corpus_count, total_words=model.corpus_total_words
)
gensim.models.fasttext.save_facebook_model(model, "test.bin")`
I am with gensim 3.8.3.

**Comment by ClementViricel** [comment] 2020-09-11 11:43
In order to understand, i have printed the assertion conditions before and after build_vocab and before and after training.
It seems that before build vocab `len(model.wv)` and `vocab_n (= model.wv.vectors_vocab.shape[0])`are equal (500 496 and 500 496 in my case).
After `build_vocab(..., update = True)` the remaining are not equel anymore (506 278 and 503 387).
This behavious is weird because it implies that the vocab size related to `model.wv.vectors_vocab` is not equal to the vocab size from `model.wv` 
After and before training nothing change, therefore on save the assertion is broken.

**Comment by gojomo** [comment] 2020-09-12 20:05
A test to trigger this error is now in #2944. Remedying the error in #2943 isn't enough to prevent the problem.

**Closed** 2020-10-15 22:19 UTC
Labels: bug

**Comment by anastasia-zhukova** [comment] 2021-02-26 16:02
Hi. I wanted to fine-tune the model on the domain-specific data, and got this Assertion error: 

26-02-2021 16:57:53 - (gensim.models.base_any2vec)[INFO][base_any2vec]: training on a 20622110 raw words (5857397 effective words) took 39.2s, 149560 effective words/s
Traceback (most recent call last):
  File "C:\Users\AnastasiaZhukova\PyCharmProjects\TestNN\venv\lib\site-packages\gensim\models\_fasttext_bin.py", line 668, in save
    _save_to_stream(model, fout_stream, fb_fasttext_parameters, encoding)
  File "C:\Users\AnastasiaZhukova\PyCharmProjects\TestNN\venv\lib\site-packages\gensim\models\_fasttext_bin.py", line 631, in _save_to_stream
    _input_save(fout, model)
  File "C:\Users\AnastasiaZhukova\PyCharmProjects\TestNN\venv\lib\site-packages\gensim\models\_fasttext_bin.py", line 575, in _input_save
    assert vocab_n == len(model.wv.vocab)
AssertionError

**Comment by mpenkov** [comment] 2021-02-26 23:22
What version of gensim are you using @anastasia-zhukova ?

**Comment by anastasia-zhukova** [comment] 2021-03-01 09:52
@mpenkov 3.8.3

**Comment by mpenkov** [comment] 2021-03-01 10:29
Are you able to share code that reproduces your problem?

**Comment by anastasia-zhukova** [comment] 2021-03-01 10:52
Sure
`train_text_df = pd.read_csv(os.path.join("..", config.RESOURCE_PATH, "text_train_data.csv"), index_col=[0])
sents = []
for text_val in train_text_df["text"].values:
    sents.append(text_val.split(", "))
# sent = [['lord', 'of', 'the', 'rings'], ['lord', 'of', 'the', 'semi-groups']]
model = load_facebook_model(os.path.join("..", config.MODEL_PATH))
model.build_vocab(sents, update=True)
model.train(sentences=sents, total_examples = len(sents), epochs=10)
gensim.models.fasttext.save_facebook_model(model, os.path.join("..", config.RESOURCE_PATH, "cc.de.300.tuned.bin"))`

Followed the tutorial from https://radimrehurek.com/gensim/models/fasttext.html#gensim.models.fasttext.load_facebook_model

**Comment by mpenkov** [comment] 2021-03-01 12:37
Thank you. What are the values of config.RESOURCE_PATH and config.MODEL_PATH?

Ideally, your reproducible example should be something that I (or another developer) can run here locally on my machine and get the same result as you do. We can then try to do something about the bug.

**Comment by anastasia-zhukova** [comment] 2021-03-01 12:47
I can't share the data to make the code reproducible because it is commercial data. I removed the paths because they have no influence on the code but added a name of the fasttext model that I am using. A column "text" in a csv file contains strings with tokens that are separated with ", ". 

```python 
train_text_df = pd.read_csv("text_train_data.csv", index_col=[0])
sents = []
for text_val in train_text_df["text"].values:
         sents.append(text_val.split(", "))
# sents = [['lord', 'of', 'the', 'rings'], ['lord', 'of', 'the', 'flies']]
model = load_facebook_model("cc.de.300.bin")
model.build_vocab(sents, update=True)
model.train(sentences=sents, total_examples = len(sents), epochs=10)
gensim.models.fasttext.save_facebook_model(model, "cc.de.300.tuned.bin"))
```

**Comment by mpenkov** [comment] 2021-03-01 13:08
I understand that you cannot share commercial data. Can you reproduce the problem using other data that you can share?

**Comment by gojomo** [comment] 2021-03-01 17:35
Does the problem reproduce if you try in the 4.0.0-beta, as can be installed locally for you per instructions at <https://groups.google.com/g/gensim/c/5mAeWrQN7lg/m/eMhYpktCAAAJ>? 

If it does not, then its likely an already-fixed bug – after all, this issue was closed-as-fixed after a test case was created that showed the problem in 3.8.x, and didn't in `develop` – and the recommendation would just be: use the 4.0.0 prerelease(s) as a workaround.

**Comment by anastasia-zhukova** [comment] 2021-03-01 18:19
Here is a snippet that can be reproduced with the attached data: [train_voc.zip](https://github.com/RaRe-Technologies/gensim/files/6063590/train_voc.zip) 
```python 
import json
import gensim

with open("train_voc.json", "r") as file:
    sents = json.load(file)
model = gensim.models.fasttext.load_facebook_model("cc.de.300.bin")
model.build_vocab(sents, update=True)
model.train(sentences=sents, total_examples = len(sents), epochs=2)
gensim.models.fasttext.save_facebook_model(model, "cc.de.300.tuned.bin")
```
Link to the German model: https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.de.300.bin.gz 

What I get in my debugging state: 
![2021-03-01_19-16-07](https://user-images.githubusercontent.com/6137243/109540457-c0b0fa00-7ac2-11eb-979c-b772430c27e7.png)

**Comment by anastasia-zhukova** [comment] 2021-03-02 09:31
gensim-4.0.0beta fixed the issue, thanks! 

For everybody who will find this thread, the script that worked with 4.0.0beta to fine-tune the model and then save it (the syntax for model.train has changed a bit): 
```python
import json
import gensim

with open("train_voc.json", "r") as file:
    sents = json.load(file)

model = gensim.models.fasttext.load_facebook_model("cc.de.300.bin")
model.build_vocab(sents, update=True)
model.train(corpus_iterable=sents, total_examples = len(sents), epochs=2)
gensim.models.fasttext.save_facebook_model(model, "cc.de.300.tuned.bin")
```
A data file if someone wants to reproduce: [train_voc.zip](https://github.com/RaRe-Technologies/gensim/files/6063590/train_voc.zip)

**Comment by pankaja0285** [comment] 2021-12-04 03:53
> gensim-4.0.0beta fixed the issue, thanks!
> 
> For everybody who will find this thread, the script that worked with 4.0.0beta to fine-tune the model and then save it (the syntax for model.train has changed a bit):
> 
> ```python
> import json
> import gensim
> 
> with open("train_voc.json", "r") as file:
>     sents = json.load(file)
> 
> model = gensim.models.fasttext.load_facebook_model("cc.de.300.bin")
> model.build_vocab(sents, update=True)
> model.train(corpus_iterable=sents, total_examples=len(sents), epochs=2)
> gensim.models.fasttext.save_facebook_model(model, "cc.de.300.tuned.bin")
> ```
> 
> A data file if someone wants to reproduce: [train_voc.zip](https://github.com/RaRe-Technologies/gensim/files/6063590/train_voc.zip)

@anastasia-zhukova
I was able to train the additional documents, but I am not sure how to see if the additional documents are really part of the retrained model.

How do I check the vocab_n that you have shown as a screenshot of your debug window?
