### ISSUE TITLE
gensim/word2vec: TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Hightham** [RaRe-Technologies/gensim#2422] opened 2019-03-19 10:58 UTC
#### Problem description

I'm trying to establish the embedding layr and the  weights which will be shown in the code bellow
 using my training input which is in the form of  a lists of tokenized questions plus the vocabulary ( i loaded my data using pandas) 
also i made sure to eliminate all integers from my data .

#### Steps/code/corpus to reproduce

```python  
embedding_weights = train_word2vec(
    X_train, vocab['w2idx'], 
    num_features=embedding_dim, 
    min_word_count=min_word_count, 
    context=context)
input_shape = (sequence_length,)
model_input = Input(shape=input_shape)
layer = Embedding(
    len(vocab['idx2w']),
    embedding_dim,
    input_length=sequence_length,
    name="embedding"
)(model_input)
layer = Dropout(dropout_prob[0])(layer)`
```

and this is the error i keep on getting

```
  File "<ipython-input-13-76e01a83efc1>", line 3, in <module>
    min_word_count=min_word_count, context=context)
  File "C:\Users\ACER\Pod_Dsgn_Chatbot\Wor2vec.py", line 43, in train_word2vec
    for key, word in vocabulary_inv.items()}
  File "C:\Users\ACER\Pod_Dsgn_Chatbot\Wor2vec.py", line 43, in <dictcomp>
    for key, word in vocabulary_inv.items()}
  File "C:\Users\ACER\Anaconda3\envs\py37\lib\site-packages\gensim\utils.py", line 1398, in new_func1
    return func(*args, **kwargs)
  File "C:\Users\ACER\Anaconda3\envs\py37\lib\site-packages\gensim\models\word2vec.py", line 821, in __getitem__
    return self.wv.__getitem__(words)
  File "C:\Users\ACER\Anaconda3\envs\py37\lib\site-packages\gensim\models\keyedvectors.py", line 171, in __getitem__
    return vstack([self.get_vector(entity) for entity in entities])
TypeError: 'int' object is not iterable`
```

#### Versions

```python 3.6.8
 platform version: '1.0.8'
 sys version:'3.6.8 |Anaconda custom (64-bit)| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)]'
 numpy version: '1.15.4'
scipy version: '1.2.0'
 gensim version: '3.4.0'
FAST_VERSION 1
```

**Comment by piskvorky** [comment] 2019-03-19 11:01
Your version of Gensim is too old; try upgrading.

**Comment by Hightham** [comment] 2019-03-19 11:02
My version was 3.7.0 and it showed the same issue as well, so i downgraded it and the problem persisted

**Comment by piskvorky** [comment] 2019-03-19 11:03
OK. Can you better format the steps to reproduce as well as the stack trace, so we can see what it says?

**Comment by Hightham** [comment] 2019-03-19 12:59
So, i just re-upgraded the version of gensim to the latest.
I haven't done much when it comes to the steps 
i just imported the libraries, set my variables, loaded my data ( input and vocabulary)
and then the code lines that were shown above.
but i still get the same error

> `
  File "C:\Users\ACER\Anaconda3\envs\py37\lib\site-packages\gensim\models\keyedvectors.py", line 
   349, in __getitem__
    return vstack([self.get_vector(str(entity)) for str(entity) in entities])

   TypeError: 'int' object is not iterable`

**Comment by piskvorky** [comment] 2019-03-19 13:28
Please post the steps (what you're running) and full trace back, in a readable format.

**Comment by mpenkov** [comment] 2019-04-20 12:39
@Hightham I reformatted your code but it's still a bit unclear about what you're trying to achieve. Without a reproducible example, it's very difficult for us to help you.

Can you please post a _reproducible_ example? Ideally, it should be source code that we can copypasta into an interpreter and run. If your example relies on some data, make that data available as well, but keep it as small as possible.

Given that it's been over a month since we've hear from you, I'm closing this for now.

**Closed by mpenkov** 2019-04-20 12:39 UTC

**Comment by andreamoro** [comment] 2019-10-30 07:12
I assume the OP is trying to get the list of words part of the model?
I have the same issue.

A ``` print (enumerate(model.vocabulary)) ``` or print (model.vocabulary) ```  produces the same message : 'Word2VecVocab' object is not iterable.

So the question persist: How can a list of words part of the model can be retrieved?

Thanks

**Comment by piskvorky** [comment] 2019-10-30 08:00
@andreamoro like this:

```python
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

model = Word2Vec(common_texts, size=100, window=5, min_count=1, workers=4)
word_vectors = model.wv
print(list(word_vectors.vocab.keys()))

['minors', 'graph', 'system', 'trees', 'eps', 'computer', 'survey', 'user', 'human', 'time', 'interface', 'response']
```

[Documentation of `KeyedVectors`](https://radimrehurek.com/gensim/models/keyedvectors.html) = the class holding the trained word vectors.

@mpenkov listing the model vocab is a reasonable task, but I couldn't find it in the documentation either. I had to look at the source. Maybe we can add it somewhere? API ref? Tutorial? @andreamoro where would you expect / look for this information?

**Comment by andreamoro** [comment] 2019-10-30 10:45
Thanks for returning so fast @piskvorky .
Unless mistaken, I've read there was a vocabulary iterator exposed as an object of model. 
I believe something like ```model.vocabulary.keys()``` and ```model.vocabulary.values()``` would be more immediate?

**Comment by piskvorky** [comment] 2019-10-30 11:47
I'm not sure about that. Where did you read that?

**Comment by andreamoro** [comment] 2019-10-30 18:54
@piskvorky just found again the stuff I was talking about this morning.
See [here](https://stackoverflow.com/questions/35596031/gensim-word2vec-find-number-of-words-in-vocabulary):

**Comment by dean-rahman** [comment] 2022-03-22 11:47
Hello and thank you for your work.
I am getting the following
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-15d6bf5786ae>](https://localhost:8080/#) in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'bigram = gensim.models.Phrases(x) ')

5 frames
<decorator-gen-53> in time(self, line, cell, local_ns)

<timed exec> in <module>()

[/usr/local/lib/python3.7/dist-packages/gensim/models/phrases.py](https://localhost:8080/#) in learn_vocab(sentences, max_vocab_size, delimiter, progress_per, common_terms)
    426                     sentence_no, total_words, len(vocab),
    427                 )
--> 428             s = [utils.any2utf8(w) for w in sentence]
    429             last_uncommon = None
    430             in_between = []

TypeError: 'float' object is not iterable

**Comment by dean-rahman** [comment] 2022-03-22 11:50
the code for the above is at
https://github.com/dean-rahman/dean-rahman.github.io/blob/master/TopicModellingFinnishHilma.ipynb
