### ISSUE TITLE
Error: from scipy.sparse import sparsetools

### ISSUE THREAD

**Issue by ghost** [RaRe-Technologies/gensim#632] opened 2016-03-23 05:20 UTC
Hello,

After installation into Python 2.7, WinPython version, I got this error:

import gensim

  File "D:\_devs\Python01\WinPython-64-2710\python-2.7.10.amd64\lib\site-packages\gensim\models\lsimodel.py", line 59, in <module>
    from scipy.sparse import sparsetools

ImportError: cannot import name sparsetools

How can I resolve the issue (it seems sparsetools is deprecated in Scipy)

Thanks so much

**Comment by piskvorky** [comment] 2016-03-23 10:07
Related to #462 and #557 .

**Comment by tmylk** [comment] 2016-03-23 11:24
@arita291 Did you use anaconda, windows wheel to install or did you build from source?

Downgrading to scipy 0.16 is a temporary workaround.
A permanent fix would be https://github.com/scipy/scipy/issues/5348

**Comment by arita291** [comment] 2016-03-23 15:04
Hi,
Winpython and install with  !pip install gensim  in Python 2.7

Best is to donwgrade to scipy 0.16 ?

**Comment by tmylk** [comment] 2016-10-06 06:20
It imports in scipy 0.18 on linux ok.
Closing as can't reproduce

**Closed by tmylk** 2016-10-06 06:20 UTC
