### ISSUE TITLE
LDA and LSI consume so much RAM then makes my PC freeze

### ISSUE THREAD

**Issue by vampire1306** [RaRe-Technologies/gensim#737] opened 2016-06-07 04:27 UTC
Here is my gensim info:

Metadata-Version: 1.1
Name: gensim
Version: 0.12.4

> View Gensim info
number of docs in raw data: 10000
Raw data file size on disk: 59959967 bytes (59.96 Mb)
++++++++++++++++++++++++++++++++++
number of postID in list post ID file: 10000
Post ID file size on disk: 133709 bytes (0.13 Mb)
++++++++++++++++++++++++++++++++++
begin to load dictionary
loading dictionary runtime: 0.222123 seconds
Dictionary(386051 unique tokens: [u'ki\xeau h\xe3nh', u'robot tr\u1ebb qu\u1ed1c t\u1ebf', u'l\u01b0\u1ee3t', u'c\xe1 \u0111u\u1ed1i', u'ng\u01b0 s\u01b0 merlion']...)
Dict memory usage: 64 bytes (0.00 Mb)
Dict file size on disk: 10966447 bytes (10.97 Mb)
++++++++++++++++++++++++++++++++++
begin to load corpus
loading corpus runtime: 0.000898 seconds
MmCorpus(10000 documents, 385984 features, 2075105 non-zero entries)
Corpus memory usage: 64 bytes (0.00 Mb)
Corpus file size on disk: 24217158 bytes (24.22 Mb)
++++++++++++++++++++++++++++++++++
number of stop words 77
Stop words memory usage: 776 bytes (0.00 Mb)
Stop words file size on disk: 688 bytes (0.00 Mb)

`

	def get_corpus(self):
		if(self.corpus == None):
			print "begin to load corpus"
			start = timeit.default_timer()
			self.corpus = MmCorpus(self.corpus_file_path)
			print("loading corpus runtime: %f seconds" %((timeit.default_timer() - start)))
		return self.corpus

	def get_dict(self):
		if(self.dict == None):
			print "begin to load dictionary"
			start = timeit.default_timer()
			self.dict = Dictionary().load(self.dict_file_path)
			print("loading dictionary runtime: %f seconds" %((timeit.default_timer() - start)))
		return self.dict

	def find_topics_by_lda(self, num_topics):
		print "Begin to find %d topics by lda" % num_topics
		start = timeit.default_timer()
		id2word = self.get_dict()
		mm = self.get_corpus()
		lda = ldamodel.LdaModel(corpus=mm, id2word=id2word, num_topics=num_topics, update_every=1, chunksize=2500, passes=1)
		print("finding topics by lda runtime: %f seconds" %((timeit.default_timer() - start)))
		return lda

	def find_topics_by_lsi(self, num_topics):
		print "Begin to find %d topics by lsi" % num_topics
		start = timeit.default_timer()
		id2word = self.get_dict()
		mm = self.get_corpus()
		lsi = lsimodel.LsiModel(corpus=mm, id2word=id2word, num_topics=num_topics)
		print("finding topics by lsi runtime: %f seconds" %((timeit.default_timer() - start)))
		return lsi
`

When I try LSI, it consumes up to 1.8Gb Ram and just goes on forever.
So I try LDA, it consumes to 4.9 Gb Ram and freezes my PC
Why this happens, my data is much smaller than the test data in the tutorial document?

**Comment by tmylk** [comment] 2016-06-07 14:46
Hi @vampire1306. This is very odd.
 Have you managed to successfully run the LDA tutorial as in https://github.com/piskvorky/gensim/blob/develop/docs/notebooks/Topics_and_Transformations.ipynb ?

Do you get any errors or exceptions in the log?

**Comment by gojomo** [comment] 2016-06-07 15:59
Also: What OS and how much RAM is available? What Python version?

**Comment by vampire1306** [comment] 2016-06-08 02:23
I update result of LSI first.
System Info:

> Os: Ubuntu 16.04 (64 bit)
> Ram: 8 Gb
> Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8
> Home's free space: 23Gb (I store gensim here)
> System's free space: 18Gb
> Python 2.7.11+

Test with LSI:

> Ram usage: ~1.875 Gb (stable)
> %Cpu(s): 13,8 us,  0,3 sy,  0,0 ni, 85,6 id,  0,3 wa,  0,0 hi,  0,0 si,  0,0 st  (stable)

Here's the log:

> 2016-06-08 08:57:09,175 : INFO : accepted corpus with 5000 documents, 58032 features, 1044099 non-zero entries
> 2016-06-08 08:57:09,209 : INFO : using serial LSI version on this node
> 2016-06-08 08:57:09,209 : INFO : updating model with new documents
> 2016-06-08 08:57:12,063 : INFO : preparing a new chunk of documents
> 2016-06-08 08:57:12,225 : INFO : using 100 extra samples and 2 power iterations
> 2016-06-08 08:57:12,225 : INFO : 1st phase: constructing (359445, 600) action matrix
> 2016-06-08 08:57:13,091 : INFO : orthonormalizing (359445, 600) action matrix
> 2016-06-08 09:10:20,033 : INFO : 2nd phase: running dense svd on (600, 5000) matrix
> 2016-06-08 09:10:25,608 : INFO : computing the final decomposition
> 2016-06-08 09:10:25,698 : INFO : keeping 500 factors (discarding 2.707% of energy spectrum)
> 2016-06-08 09:12:19,352 : INFO : processed documents up to #5000
> 2016-06-08 09:12:19,656 : INFO : Done Finding topics by lsi runtime: 910.640037 seconds (testing)
> 

I run LSI successfully and but it takes 910 seconds (15 minutes) to handle 5000 documents.

**Comment by vampire1306** [comment] 2016-06-08 02:35
Test with LDA:

> %Cpu(s): 12,4 us,  0,9 sy,  0,0 ni, 86,6 id,  0,2 wa,  0,0 hi,  0,0 si,  0,0 st
> Ram usage is quickly up to 3.98 Gb, I have to kill the process before my PC freezes

Here's the log:
2016-06-08 09:27:36,094 : INFO : accepted corpus with 5000 documents, 58032 features, 1044099 non-zero entries
loading testing corpus runtime: 0.006650 seconds

> 2016-06-08 09:27:36,118 : INFO : using symmetric alpha at 0.002
> 2016-06-08 09:27:36,118 : INFO : using symmetric eta at 0.002
> 2016-06-08 09:27:36,118 : INFO : using serial LDA version on this node
> 2016-06-08 09:28:15,259 : INFO : running online LDA training, 500 topics, 1 passes over the supplied corpus of 5000 documents, updating model once every 2500 documents, evaluating perplexity every 5000 documents, iterating 50x with a convergence threshold of 0.001000
> 2016-06-08 09:28:15,279 : WARNING : too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
> 2016-06-08 09:28:16,751 : INFO : PROGRESS: pass 0, at document #2500/5000
> 2016-06-08 09:29:13,433 : INFO : merging changes from 2500 documents into a model of 5000 documents
> Killed

**Comment by vampire1306** [comment] 2016-06-08 04:45
I try to test LDA on Ubuntu's terminal mode.
The corpus is of 100.000 documents.
It consumes up to 7.5 Gb Ram, then throw Memory exception.
The demo in the docs, it is said that the data includes 3931787 documents.

> MmCorpus(3931787 documents, 100000 features, 756379027 non-zero entries)

The LDA test  with corpus of 10.000 is successful (no exception)

**Comment by tmylk** [comment] 2016-10-18 14:38
Closing as can't reproduce.

**Closed by tmylk** 2016-10-18 14:38 UTC
Labels: bug, medium difficult
