### ISSUE TITLE
add document to Lsi Model dynamically

### ISSUE THREAD

**Issue by adoniswu** [RaRe-Technologies/gensim#1993] opened 2018-03-22 09:59 UTC
#### Description
gensim version：3.1.0
my code:
lsi = models.LsiModel.load(path)
lsi.add_document(corpus, chunksize=50000)

at the first time, the lsi model can add 50000 corpus in to lsi model,
but once more, report an error, i check the core file which shows the second line code running error
i tried to change the size of chunksize, but when reach the size of 50000, and then i got the same error!
![wechatimg5850](https://user-images.githubusercontent.com/27185685/37763377-d4d6f494-2df9-11e8-8bcc-f6d3b20907f2.jpeg)
![wechatimg5851](https://user-images.githubusercontent.com/27185685/37763380-d6246962-2df9-11e8-894d-7a1b132a6c39.jpeg)

**Comment by menshikh-iv** [comment] 2018-03-22 11:53
Hi @adoniswu, please share your model & corpus, I'll try to reproduce.
I'll try to guess - the problem in `corpus` (this contains word index that doesn't contain in the model dictionary.

**Comment by adoniswu** [comment] 2018-03-22 12:36
hi, @menshikh-iv ,thanks for your reply，i just get bags(id2word) in the first 50000 corpus. that's to say the bags is not enough for the whole corpus. but the whole corpus dynamically increase.  i can not get the whole bags at the first time. how to deal with this problem.

**Comment by menshikh-iv** [comment] 2018-03-22 12:46
@adoniswu 
1. (best) Fit Dictionary only once on big data sample and use it later. Don't worry about tokens that you missed, that's fine for practical usage if your sample is large enough.
2. Use [HashDictionary](https://radimrehurek.com/gensim/corpora/hashdictionary.html), this based on hashing-trick (is subject to collisions)

Looks like I'm guessing a problem, so I close the issue.

**Closed by menshikh-iv** 2018-03-22 12:46 UTC
Labels: need info

**Comment by adoniswu** [comment] 2018-03-22 12:48
thanks
