### ISSUE TITLE
Investigate wheel filesize

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3238] opened 2021-09-17 09:23 UTC
We build wheels for 4 platforms x 4 Python versions = 16 wheels per release. Each wheel is 25 MB (why so large?), so that's > 400 MB per release! I can see 10 GB disappearing quickly.

How do other projects with extensive wheel support (scikit-learn?) solve this?

_Originally posted by @piskvorky in https://github.com/RaRe-Technologies/gensim/issues/3237#issuecomment-921580397_

**Comment by gojomo** [comment] 2021-09-17 21:37
Somewhat of a duplicate of #1783.

Much of the `test_data` may not even be currently used. In #2967 I suggested:

> * running the full test suite against a test_data directory where we're logging file-touches - so that obsolete, untouched files can be finally discarded

This could be as simple as doing it one time on a developer machine where the filesystem tracks `atime` (last-accessed time), then deleting all files not accessed during a full-run. *If* the CI build/test machine filesystems support `atime` (or would allow other hooks to be added somehow), it could even be added to the build process: log, or possibly even fail, if a 'full test run' doesn't touch some of the `test_data` files. 

Most of `test_data` could also be left out of user-distros like wheels entirely. There might be some smaller subset we want there for ease of use in example-code - maybe, a `demo_data` in the project source alongside the `test_data`, and only `demo_data` goes into user-builds?

I'd still want to provide some robust 1-liner that lets even end-users, who want to run the full test suite, get all `test_data`. Perhaps, something that *pulls the corresponding build-tag/commit `test_data` dir directly from github*? Unsure of best practice here, but we'd want to be careful that, for example, `develop` HEAD CI test/build runs always use the exact-sync'd test files, not something that might even be a while-warming-up moment-later.

**Comment by piskvorky** [comment] 2021-09-18 09:10
Oh wow,  I clean forgot about that thread. Thanks for the link.

I'll revisit https://github.com/RaRe-Technologies/gensim/issues/2967#issuecomment-791358743 and clean up / drop the test data as part of the solution there.

Closing this ticket – nothing more to investigate here.

**Closed by piskvorky** 2021-09-18 09:10 UTC
Labels: housekeeping
