### ISSUE TITLE
nosetest failing on develop

### ISSUE THREAD

**Issue by dsquareindia** [RaRe-Technologies/gensim#709] opened 2016-05-27 14:13 UTC
One test is failing on my local machine in the develop branch. It is up to date with upstream/develop. I'm using ubuntu linux. Here's the traceback:
```
FAIL: test_getitem_sparse2sparse (gensim.test.test_sharded_corpus.TestShardedCorpus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/devashish/gensim/gensim/test/test_sharded_corpus.py", line 169, in test_getitem_sparse2sparse
    self.assertTrue(isinstance(ilist, sparse.csr_matrix))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
gensim.corpora.sharded_corpus: INFO: Initializing sharded corpus with prefix test-temp-11967864/shcorp.11967864.tmp
gensim.corpora.sharded_corpus: INFO: Building from corpus...
gensim.corpora.sharded_corpus: WARNING: Couldn't find number of features, trusting supplied dimension (1000)
gensim.corpora.sharded_corpus: INFO: Running init from corpus.
gensim.corpora.sharded_corpus: INFO: Chunk no. 0 at 6.30000000115e-05 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 1 at 0.011418 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 2 at 0.022527 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 3 at 0.03352 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 4 at 0.044551 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 5 at 0.055306 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 6 at 0.06637 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 7 at 0.077533 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 8 at 0.088479 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 9 at 0.099604 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Built 10 shards in 0.11047 s.
gensim.corpora.sharded_corpus: INFO: Saving ShardedCorpus object to test-temp-11967864/shcorp.11967864.tmp
gensim.utils: INFO: saving ShardedCorpus object under test-temp-11967864/shcorp.11967864.tmp, separately None
gensim.utils: INFO: not storing attribute current_shard
gensim.utils: INFO: not storing attribute current_offset
gensim.utils: INFO: not storing attribute current_shard_n
gensim.corpora.sharded_corpus: INFO: Initializing sharded corpus with prefix test-temp-11967864/shcorp.11967864.tmp.sparse
gensim.corpora.sharded_corpus: INFO: Building from corpus...
gensim.corpora.sharded_corpus: WARNING: Couldn't find number of features, trusting supplied dimension (1000)
gensim.corpora.sharded_corpus: INFO: Running init from corpus.
gensim.corpora.sharded_corpus: INFO: Chunk no. 0 at 5.50000000317e-05 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 1 at 0.013801 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 2 at 0.027472 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 3 at 0.041387 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 4 at 0.055006 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 5 at 0.068989 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 6 at 0.082269 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 7 at 0.095535 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 8 at 0.108788 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Chunk no. 9 at 0.121748 s
gensim.corpora.sharded_corpus: DEBUG: Current chunk dimension: 100 x 1000
gensim.corpora.sharded_corpus: INFO: Built 10 shards in 0.134708 s.
gensim.corpora.sharded_corpus: INFO: Saving ShardedCorpus object to test-temp-11967864/shcorp.11967864.tmp.sparse
gensim.utils: INFO: saving ShardedCorpus object under test-temp-11967864/shcorp.11967864.tmp.sparse, separately None
gensim.utils: INFO: not storing attribute current_shard
gensim.utils: INFO: not storing attribute current_offset
gensim.utils: INFO: not storing attribute current_shard_n
gensim.corpora.sharded_corpus: INFO: Initializing sharded corpus with prefix test-temp-11967864/shcorp.11967864.tmp
gensim.corpora.sharded_corpus: INFO: Cloning existing...
gensim.utils: INFO: loading ShardedCorpus object from test-temp-11967864/shcorp.11967864.tmp
gensim.utils: INFO: setting ignored attribute current_shard to None
gensim.utils: INFO: setting ignored attribute current_offset to None
gensim.utils: INFO: setting ignored attribute current_shard_n to None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 286 tests in 196.972s

FAILED (SKIP=8, failures=1)
```

**Comment by tmylk** [comment] 2016-05-27 15:52
Could you please post the pip freeze output as well?

**Comment by dsquareindia** [comment] 2016-05-27 17:10
@tmylk here's the output:
```
backports-abc==0.4
backports.ssl-match-hostname==3.4.0.2
boto==2.39.0
bz2file==0.98
conda==4.0.5
conda-env==2.4.5
config==0.3.7
cycler==0.10.0
Cython==0.24
decorator==4.0.9
-e git+https://github.com/dsquareindia/gensim.git@e1d3cc2a005f6326973e94152292d6fe04945b85#egg=gensim
httpretty==0.8.10
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
MySQL-python==1.2.5
nbconvert==4.1.0
nbformat==4.0.1
notebook==4.1.0
numpy==1.10.4
path.py==0.0.0
pexpect==3.3
pickleshare==0.5
ply==3.8
ptyprocess==0.5
pycairo==1.10.0
pycosat==0.6.1
pycrypto==2.6.1
Pygments==2.1.1
pyparsing==2.0.3
python-dateutil==2.5.1
pytz==2016.2
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.1.1
requests==2.8.1
-e git+https://github.com/dsquareindia/scikit-learn.git@3ab37f72ca33eb4d6886cefb5ed2b6fc83a56c2a#egg=scikit_learn
scipy==0.17.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
smart-open==1.3.2
terminado==0.5
tornado==4.3
traitlets==4.2.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by tmylk** [comment] 2016-10-05 13:13
Closing as can't reproduce

**Closed by tmylk** 2016-10-05 13:13 UTC
Labels: bug
