### ISSUE TITLE
Understanding the topic significance of LDA

### ISSUE THREAD

**Issue by simon19891101** [RaRe-Technologies/gensim#3045] opened 2021-02-12 20:21 UTC
#### Problem description

Hi there, I noticed that the print_topics() of LDA models says "Get the most significant topics" and "The number of topics to be selected, if -1 - all topics will be in result (ordered by significance)" in the documentation https://radimrehurek.com/gensim/models/ldamodel.html. However, I failed to identify the logic behind it. May I know what mechanisms are utilised to calculate the topic significance? Much appreciated :)

#### Steps/code/corpus to reproduce

Sorry. This is not an issue to reproduce.

#### Versions

Sorry. This is not an issue related to environment versions. The documentation I'm reading is for Gensim 4.0.0.

**Comment by piskvorky** [comment] 2021-02-12 20:42
Duplicate of #3044. Please don't spam our issue tracker.

**Closed by piskvorky** 2021-02-12 20:42 UTC

**Comment by simon19891101** [comment] 2021-02-12 21:30
Sorry. Gonna modify and reopen the old one. Cheers.

Radim Řehůřek <notifications@github.com> 于 2021年2月13日周六 09:43写道：
