### ISSUE TITLE
Broken link in the tutorial code

### ISSUE THREAD

**Issue by johnwatson11218** [RaRe-Technologies/gensim#2885] opened 2020-07-16 07:31 UTC
#### Problem description

Reading the tutorial there is a sample url corpus at :

https://radimrehurek.com/gensim/auto_examples/core/mycorpus.txt

That link appears to be broken 
#### Steps/code/corpus to reproduce

click the link on the second page of the tutorial 

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by piskvorky** [comment] 2020-07-16 07:45
Which tutorial?

In any case, fixed for now by copying the missing file. To be be fixed later by replacing the link with simple in-line code. 
Duplicate of #2872 .

**Comment by johnwatson11218** [comment] 2020-07-16 08:07
The main one for gensim, the part about vector spaces and transforms,
second page where it starts to use smart-open. Sorry not more specific, I
am on an ipad.

**Comment by piskvorky** [comment] 2021-06-06 10:19
Thanks for reporting; closing as duplicate of #2872.

**Closed by piskvorky** 2021-06-06 10:19 UTC
