### ISSUE TITLE
Pre-installed container image with gensim

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#497] opened 2015-10-22 13:45 UTC
Use Docker (or similar) technology to distribute a turn-key environment for trying out gensim.

Discussed on the [mailing list](https://groups.google.com/forum/#!searchin/gensim/docker/gensim/DYad1y74ZQA/gCXZZwKWDAoJ) but never realized. CC @svanschalkwyk.

The goals are:
- no extra installations (all dependencies already there)
- includes a data set for trying things out, along with instructions / tutorial scripts
- other?

**Comment by svanschalkwyk** [comment] 2015-10-22 15:17
Hello Radim
I now run all my apps in Docker where I can.
Let me look at what I can do. Anyone have a preference for a distro?
Regards
Steph

**Comment by tmylk** [comment] 2015-10-22 23:17
A vote for Ubuntu as that seems to be what most of users run.

**Comment by piskvorky** [comment] 2015-10-23 03:55
Yes, ubuntu looks like a good choice!

**Comment by tmylk** [comment] 2016-01-09 21:20
@svanschalkwyk did you have any luck on creating an ubuntu docker with gensim?

**Comment by svanschalkwyk** [comment] 2016-01-10 01:15
Hi Lev
Yes. I'm quickly recreating one for you.
Question - this is the first time I'm running Py3.4 and I'm running into
errors installing Gensim  with "easy_install --upgrade gensim"

​"File "/tmp/easy_install-gpk5490m/httpretty-0.8.10/setup.py", line 78, in
<lambda>
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133:
ordinal not in range(128)
"
I rarely work in Python anymore, so any help would be appreciated.
I'll post the dockerfiles to my github tomorrow. Will post the links.
Thanks,
Steph
​



_______________________________________________
*Remcam LLC <http://remcam.net>  *                                 *
http://remcam.net
<http://remcam.net>*
Voice/SMS:  +1 312 281 8982 <312+281+8982> (all lines)
Skype: svanschalkwyk
LinkedIn <http://linkedin.com/in/vanschalkwyk>
_______________________________________________

**Comment by svanschalkwyk** [comment] 2016-01-10 05:59
Hi Lev
Here is the first, very basic one. I have others with various versions of
CUDA as well. Feel free to send me requests for additional functionality.

dockerfile:

FROM ubuntu:15.10
MAINTAINER Steph van Schalkwyk <step@remcam.net>
ENV DEBIAN_FRONTEND noninteractive

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN mkdir -p /home/gensim_user/gensim
WORKDIR /home/gensim_user

RUN apt-get update && apt-get install -y wget build-essential python3-dev
python3-setuptools python3-numpy python3-scipy python3-pip libatlas-dev
libatlas3gf-base
RUN wget -nv -O /tmp/gensim-0.12.3.tar.gz
https://pypi.python.org/packages/source/g/gensim/gensim-0.12.3.tar.gz#md5=9581467d50ec6da0097939464c422d00

RUN tar -xzvf /tmp/gensim-0.12.3.tar.gz -C /home/gensim_user/gensim
--strip-components=1
RUN cd /home/gensim_user/gensim
RUN python3 /home/gensim_user/gensim/setup.py install

Copy the text above to a file named "dockerfile" into a directory. From a
terminal/cmd in that directory, execute the build and run.

Build with:
"docker build -t gensim ."
Run with:
"docker run -ti --rm --name gensim gensim bash"

The "docker run" command above will put you into a /bin/bash in the
directory /home/gensim_user. CD to gensim and try the tutorials.

Steph


_______________________________________________
*Remcam LLC <http://remcam.net>  *                                 *
http://remcam.net
<http://remcam.net>*
Voice/SMS:  +1 312 281 8982 <312+281+8982> (all lines)
Skype: svanschalkwyk
LinkedIn <http://linkedin.com/in/vanschalkwyk>
_______________________________________________

**Comment by tmylk** [comment] 2016-01-10 06:26
Thanks, where is a good place to host the container so that it could be pulled?

The error above should be resolved by installing smart_open on a clean virtualenv. (httpretty requests dependency is the cause)

**Comment by tmylk** [comment] 2016-01-11 15:28
Is this a duplicate of #579?

**Comment by piskvorky** [comment] 2016-01-12 02:08
The other way around, more likely.

**Comment by zmarty** [comment] 2016-01-12 04:52
Thanks for linking the items. Since I already have an image published to the repository that is being auto-built (compiled) by docker with an arguably cleaner Dockerfile, I suggest we use mine. See here: https://hub.docker.com/r/zmarty/python3-gensim-doc2vec/~/dockerfile/. I have tested it with my own code and it works.

Also, I have configured the images to be tagged. Right now there are two tags available: "latest" (which is the default), and "based-on-ubuntu-15.10". This opens up the possibility of having different containers based on different versions of Ubuntu or different versions of python.

The only thing that I can think that would make the container even better is to make it official, as in instead of it being located here: https://hub.docker.com/r/zmarty/python3-gensim-doc2vec/ it should be marked as official and located here: https://hub.docker.com/_/gensim/. See https://hub.docker.com/_/mysql/ for example. I can try to take this up with Docker if you wish.

**Comment by tmylk** [comment] 2016-01-12 06:32
Thanks @zmarty! An official docker container would be great

**Comment by zmarty** [comment] 2016-01-12 06:42
Sure, no problem. I will get on it. Official containers are a bit more complicated to publish because Docker has a separate team that code reviews them. Will post here if there are more requirements or when it's done, but the container itself will be identical to what is already in my link above.

**Comment by zmarty** [comment] 2016-01-15 04:40
Moving the discussion from the linked item to here.

As I was saying there, I have modified the Dockerfile to conform to the best practices guide: https://docs.docker.com/engine/articles/dockerfile_best-practices/ as suggested here: https://github.com/docker-library/official-images

I am now working on exposing the notebook as @tmylk suggested.

However, I would need to open a simpler Notebook file that does not require all the other dependencies like nltk mentioned here: https://github.com/piskvorky/topic_modeling_tutorial/blob/master/0%20-%20Intro%20%26%20Setup.ipynb

I would need a notebook which only uses gensim, something like this: https://github.com/jdwittenauer/ipython-notebooks/blob/master/Gensim.ipynb

**Can anybody please provide a small notebook example to show by default when users start the Docker image?**

**Comment by zmarty** [comment] 2016-01-15 05:48
Yet another update: I have a preliminary version that installs IPython and runs it. The image also contains an example notebook for Gensim, but as I was saying above we might need a new notebook file.

You can take a look at the Dockerfile here: https://github.com/zmarty/docker-python3-gensim-doc2vec/blob/master/based-on-ubuntu-15.10/Dockerfile

There are a few problems that I need to fix. The major one is that the version of IPython3 shipped with Ubuntu seems to keep crashing. So I will work on it to make it more stable by configuring the default version or replacing it with a new more stable version.

**Comment by tmylk** [comment] 2016-01-23 21:05
Hi @zmarty thanks for the docker file!

The ipynb files that are best to be shown on the container launch are the 4 gensim tutorials in
https://github.com/piskvorky/gensim/tree/develop/docs/notebooks

**Comment by piskvorky** [comment] 2016-01-24 01:50
I agree that we should create a "welcome notebook".

Or, we could use the existing [set of tutorials](http://radimrehurek.com/gensim/tutorial.html), which makes sense to me too.

@tmylk what do you need to fully test, merge and deploy this?

I think this is cool enough to warrant a blog post / tutorial :)

**Comment by zmarty** [comment] 2016-01-28 03:58
I am back from vacation. I will try to use the four tutorials linked above and report back here.

**Comment by tmylk** [comment] 2016-01-28 12:02
Welcome back!

Changes needed before publishing a Gensim Docker container:
- [ ] Make it official and share acess credentials among gensim collaborators  https://hub.docker.com/_/gensim/
- [ ] start ipython notebook on container start-up
- [ ] Create a very basic introduction to gensim "A gensim beginner ipython notebook".
- [ ] Convert [medium-level tutorials](http://radimrehurek.com/gensim/tutorial.html) to ipynb format and add to the container
- [ ] Add [Specialised ipython notebook tutorials](https://github.com/piskvorky/gensim/tree/develop/docs/notebooks) added to the container

**Comment by piskvorky** [comment] 2016-01-28 13:17
@tmylk are you asking @zmarty to do it, or will you, or should I...?

**Comment by tmylk** [comment] 2016-01-28 13:28
@zmarty Do you have time to do this? I won't be able to look into it until March

**Comment by zmarty** [comment] 2016-01-28 17:31
I can do items 1 and 2. For now we can use the already existing tutorials. Then when you get time to create new tutorials we will just slightly modify the image to include them as well.

**Comment by danielbdias** [comment] 2017-01-29 17:20
Hi guys ! 

I'm working in a docker image for gensim here: https://github.com/danielbdias/gensim/tree/issue-497/docker

It is based in a Ubuntu 16.04 image with Python 3. To execute the notebooks I am using a docker-compose.yml file with jupyter notebooks config.

Can you see if the configuration is ok?

**Comment by tmylk** [comment] 2017-01-29 17:51
Great. Can it open the quickstart ipynb on start-up?

**Comment by tmylk** [comment] 2017-01-29 18:01
Also, can it check that [FAST_VERSION](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L113) > -1 ?

**Comment by danielbdias** [comment] 2017-01-29 18:08
Sure ! I will configure the ipynb to open the quickstart tutorial. 

About the FAST_VERSION, how can I check this? Is it a env variable?

**Comment by danielbdias** [comment] 2017-01-29 19:56
I updated the PR [#1121](https://github.com/RaRe-Technologies/gensim/pull/1121) with some changes in Dockerfile:

- Now the container downloads the gensim master branch to have all notebooks internally and exposes via jupyter notebook;
- When you build and start the container, the container will start jupyter in port 9000 with the quickstart ipynb

The next tasks are:

- Build a script to check FAST_VERSION;
- Make it official and share access credentials among gensim collaborators https://hub.docker.com/_/gensim/;
- Document how to download and run the docker image

**Comment by danielbdias** [comment] 2017-04-24 04:09
Hi guys !

Giving some updates on this issue after a while: I've updated the dockerfile to support WordRank, MorphologicalPriorsForWordEmbeddings, DTM and Mallet.

Is there a issue yet with the FAST_VERSION... some dependency broke the version.

Fixing this problem, I'll be able to upload a version to docker hub and create a gensim user there.

Feel free to comment any issue or give any suggestions to improve the Dockerfile !

Thanks !

**Comment by tmylk** [comment] 2017-04-27 02:18
@danielbdias Thanks a lot. Let's wait for FAST_VERSION to be fixed and then publicize it.

**Comment by menshikh-iv** [comment] 2017-10-03 06:43
Already implemented in [docker/](https://github.com/RaRe-Technologies/gensim/tree/2.3.0/docker)

**Closed by menshikh-iv** 2017-10-03 06:43 UTC
Labels: documentation, wishlist
