### ISSUE TITLE
After parsing "wikipedia-latest-pages-articles" dump, in the output (text file), numeric text were trimmed out..!

### ISSUE THREAD

**Issue by ssirasoni13** [RaRe-Technologies/gensim#2536] opened 2019-06-24 19:36 UTC
#### Problem description

After parsing Wikipedia dump file,  I took a look at the output (text file) and confirmed that numeric texts were all gone. I thoroughly looked over the source-codes of related gensim scripts, but still struggling with this issue. 

#### Steps/code/corpus to reproduce

In particular, I would like to capture certain terms like "3d printer", "web2.0", and "HTML5" inside the corpus. The code below was self-edited based on 'Pang Yang's code. I supposed the problem might be lying in the way of preprocessing in "WikiCorpus" class, but I am still having no idea how to fix this issue. Thanks for your help in advance!   

#### Versions

Please provide the output of:

```python
from __future__ import print_function
 
import logging
import os.path
import six
import sys
 
from gensim.corpora import WikiCorpus
 
if __name__ == '__main__':
    program = os.path.basename(sys.argv[0])
    logger = logging.getLogger(program)
 
    logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
    logging.root.setLevel(level=logging.INFO)
    logger.info("running %s" % ' '.join(sys.argv))
 
    # check and process input arguments
    if len(sys.argv) != 3:
        print("Using: python process_wiki.py enwiki.xxx.xml.bz2 wiki.en.text")
        sys.exit(1)
    inp, outp = sys.argv[1:3]
    space = " "
    i = 0

    
    #errors = 'ignore'
    #encoding='utf-8' 
    output = open(outp, 'w')
    wiki = WikiCorpus(inp, lemmatize=False, dictionary={})
    for text in wiki.get_texts():
        text = [x.encode('utf-8') for x in text]
        if six.PY3:
            output.write(b' '.join(text).decode('utf-8') + '\n')
        #   ###another method###
        #    output.write(
        #            space.join(map(lambda x:x.decode("utf-8"), text)) + '\n')
        else:
            output.write(space.join(text) + "\n")
        i = i + 1
        if (i % 10000 == 0):
            logger.info("Saved " + str(i) + " articles")
 
    output.close()
    logger.info("Finished Saved " + str(i) + " articles")
```

**Comment by piskvorky** [comment] 2019-06-24 19:53
The [default WikiCorpus tokenizer](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L340) employs [gensim.utils.tokenize](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/utils.py#L221), which will simply lowercase alphabetic character sequences (so, no numbers).

Just like the [WikiCorpus module description](https://radimrehurek.com/gensim/corpora/wikicorpus.html) says.

However, it seems `WikiCorpus` accepts an optional `tokenizer_func` constructor argument. So if you want a different tokenization, supply your own function there.

Closing here since this is not a bug. For open ended questions and discussions, please use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim).

**Closed by piskvorky** 2019-06-24 19:53 UTC

**Comment by ssirasoni13** [comment] 2019-06-24 20:04
> The [default WikiCorpus tokenizer](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L340) employs [gensim.utils.tokenize](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/utils.py#L221), which will simply lowercase alphabetic character sequences (so, no numbers).
> 
> Just like the [WikiCorpus module description](https://radimrehurek.com/gensim/corpora/wikicorpus.html) says.
> 
> However, it seems `WikiCorpus` accepts an optional `tokenizer_func` constructor argument. So if you want a different tokenization, supply your own function there.
> 
> Closing here since this is not a bug. For open ended questions and discussions, please use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim).

Thanks @piskvorky ! Let me figure it out myself!
