### ISSUE TITLE
value error report during training the lsi model

### ISSUE THREAD

**Issue by sherlockhoatszx** [RaRe-Technologies/gensim#1188] opened 2017-03-07 13:05 UTC
Traceback (most recent call last):
  File "generate_model_andindex.py", line 25, in <module>
    lsi = models.LsiModel(corpus_tfidf, id2word=dictionary, num_topics=500)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/lsimodel.py", line 331, in __init__
    self.add_documents(corpus)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/lsimodel.py", line 390, in add_documents
    update = Projection(self.num_terms, self.num_topics, job, extra_dims=self.extra_samples, power_iters=self.power_iters)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/lsimodel.py", line 129, in __init__
    extra_dims=self.extra_dims)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/lsimodel.py", line 709, in stochastic_svd
    u, s, vt = scipy.linalg.svd(b, full_matrices=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_svd.py", line 96, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/usr/local/lib/python2.7/dist-packages/scipy/_lib/_util.py", line 228, in _asarray_validated
    a = toarray(a)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1215, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

my code is 

```
dictionary = corpora.Dictionary.load('/new32/law/500kdic_lsi.dictionary')
print ' dictionary loaded'
corpus = corpora.MmCorpus('/new32/law/1k_corpus.mm')
print 'corpus loaded'
tfidf = models.TfidfModel(corpus)
corpus_tfidf = tfidf[corpus]
print 'starting training model'
lsi = models.LsiModel(corpus_tfidf, id2word=dictionary, num_topics=500)
print 'model trained'
lsi.save('/new32/law/5ootopic_mar7.lsi') 
```

**Comment by piskvorky** [comment] 2017-03-12 04:53
My guess is something is wrong with your data -- did you check what's inside your `corpus`?

infs and NaNs imply some sort of subtly empty/degenerate input. I say subtly because there are checks in gensim which would output a saner error message, if the input was flat out empty.

**Comment by prakhar2b** [comment] 2017-04-01 21:49
@tmylk @piskvorky Above code works completely fine on my system. Indeed, there must be something wrong with the data only. As for ```infs and NaNs``` , and other data sanity checks, another issue is already open #74

**Comment by tmylk** [comment] 2017-05-02 23:07
Closing as not reproduced

**Closed by tmylk** 2017-05-02 23:07 UTC
Labels: bug
